/*
Identity Security Cloud API - Governance Groups

Use these APIs to interact with the Identity Security Cloud platform to achieve repeatable, automated processes with greater scalability. We encourage you to join the SailPoint Developer Community forum at https://developer.sailpoint.com/discuss to connect with other developers using our APIs.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api_governance_groups_v1

import (
	"encoding/json"
)

// checks if the Connectedobject type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Connectedobject{}

// Connectedobject struct for Connectedobject
type Connectedobject struct {
	Type *Connectedobjecttype `json:"type,omitempty"`
	// ID of the object to which this reference applies
	Id *string `json:"id,omitempty"`
	// Human-readable name of Connected object
	Name *string `json:"name,omitempty"`
	// Description of the Connected object.
	Description NullableString `json:"description,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _Connectedobject Connectedobject

// NewConnectedobject instantiates a new Connectedobject object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConnectedobject() *Connectedobject {
	this := Connectedobject{}
	return &this
}

// NewConnectedobjectWithDefaults instantiates a new Connectedobject object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConnectedobjectWithDefaults() *Connectedobject {
	this := Connectedobject{}
	return &this
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *Connectedobject) GetType() Connectedobjecttype {
	if o == nil || IsNil(o.Type) {
		var ret Connectedobjecttype
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Connectedobject) GetTypeOk() (*Connectedobjecttype, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *Connectedobject) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given Connectedobjecttype and assigns it to the Type field.
func (o *Connectedobject) SetType(v Connectedobjecttype) {
	o.Type = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *Connectedobject) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Connectedobject) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *Connectedobject) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *Connectedobject) SetId(v string) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *Connectedobject) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Connectedobject) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *Connectedobject) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *Connectedobject) SetName(v string) {
	o.Name = &v
}

// GetDescription returns the Description field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Connectedobject) GetDescription() string {
	if o == nil || IsNil(o.Description.Get()) {
		var ret string
		return ret
	}
	return *o.Description.Get()
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Connectedobject) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Description.Get(), o.Description.IsSet()
}

// HasDescription returns a boolean if a field has been set.
func (o *Connectedobject) HasDescription() bool {
	if o != nil && o.Description.IsSet() {
		return true
	}

	return false
}

// SetDescription gets a reference to the given NullableString and assigns it to the Description field.
func (o *Connectedobject) SetDescription(v string) {
	o.Description.Set(&v)
}
// SetDescriptionNil sets the value for Description to be an explicit nil
func (o *Connectedobject) SetDescriptionNil() {
	o.Description.Set(nil)
}

// UnsetDescription ensures that no value is present for Description, not even an explicit nil
func (o *Connectedobject) UnsetDescription() {
	o.Description.Unset()
}

func (o Connectedobject) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Connectedobject) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if o.Description.IsSet() {
		toSerialize["description"] = o.Description.Get()
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *Connectedobject) UnmarshalJSON(data []byte) (err error) {
	varConnectedobject := _Connectedobject{}

	err = json.Unmarshal(data, &varConnectedobject)

	if err != nil {
		return err
	}

	*o = Connectedobject(varConnectedobject)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "type")
		delete(additionalProperties, "id")
		delete(additionalProperties, "name")
		delete(additionalProperties, "description")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableConnectedobject struct {
	value *Connectedobject
	isSet bool
}

func (v NullableConnectedobject) Get() *Connectedobject {
	return v.value
}

func (v *NullableConnectedobject) Set(val *Connectedobject) {
	v.value = val
	v.isSet = true
}

func (v NullableConnectedobject) IsSet() bool {
	return v.isSet
}

func (v *NullableConnectedobject) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConnectedobject(val *Connectedobject) *NullableConnectedobject {
	return &NullableConnectedobject{value: val, isSet: true}
}

func (v NullableConnectedobject) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConnectedobject) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


