/*
Identity Security Cloud API - Access Requests

Use these APIs to interact with the Identity Security Cloud platform to achieve repeatable, automated processes with greater scalability. We encourage you to join the SailPoint Developer Community forum at https://developer.sailpoint.com/discuss to connect with other developers using our APIs.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api_access_requests_v1

import (
	"encoding/json"
	"fmt"
)

// checks if the Accessrequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Accessrequest{}

// Accessrequest struct for Accessrequest
type Accessrequest struct {
	// A list of Identity IDs for whom the Access is requested. If it's a Revoke request, there can only be one Identity ID.
	RequestedFor []string `json:"requestedFor"`
	RequestType NullableAccessrequesttype `json:"requestType,omitempty"`
	RequestedItems []Accessrequestitem `json:"requestedItems"`
	// Arbitrary key-value pairs. They will never be processed by the IdentityNow system but will be returned on associated APIs such as /account-activities.
	ClientMetadata *map[string]string `json:"clientMetadata,omitempty"`
	// Additional submit data structure with requestedFor containing requestedItems allowing distinction for each request item and Identity. * Can only be used when 'requestedFor' and 'requestedItems' are not separately provided * Adds ability to specify which account the user wants the access on, in case they have multiple accounts on a source * Allows the ability to request items with different remove dates * Also allows different combinations of request items and identities in the same request * Only for use in GRANT_ACCESS type requests 
	RequestedForWithRequestedItems []Requestedfordtoref `json:"requestedForWithRequestedItems,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _Accessrequest Accessrequest

// NewAccessrequest instantiates a new Accessrequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAccessrequest(requestedFor []string, requestedItems []Accessrequestitem) *Accessrequest {
	this := Accessrequest{}
	this.RequestedFor = requestedFor
	this.RequestedItems = requestedItems
	return &this
}

// NewAccessrequestWithDefaults instantiates a new Accessrequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAccessrequestWithDefaults() *Accessrequest {
	this := Accessrequest{}
	return &this
}

// GetRequestedFor returns the RequestedFor field value
func (o *Accessrequest) GetRequestedFor() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.RequestedFor
}

// GetRequestedForOk returns a tuple with the RequestedFor field value
// and a boolean to check if the value has been set.
func (o *Accessrequest) GetRequestedForOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.RequestedFor, true
}

// SetRequestedFor sets field value
func (o *Accessrequest) SetRequestedFor(v []string) {
	o.RequestedFor = v
}

// GetRequestType returns the RequestType field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Accessrequest) GetRequestType() Accessrequesttype {
	if o == nil || IsNil(o.RequestType.Get()) {
		var ret Accessrequesttype
		return ret
	}
	return *o.RequestType.Get()
}

// GetRequestTypeOk returns a tuple with the RequestType field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Accessrequest) GetRequestTypeOk() (*Accessrequesttype, bool) {
	if o == nil {
		return nil, false
	}
	return o.RequestType.Get(), o.RequestType.IsSet()
}

// HasRequestType returns a boolean if a field has been set.
func (o *Accessrequest) HasRequestType() bool {
	if o != nil && o.RequestType.IsSet() {
		return true
	}

	return false
}

// SetRequestType gets a reference to the given NullableAccessrequesttype and assigns it to the RequestType field.
func (o *Accessrequest) SetRequestType(v Accessrequesttype) {
	o.RequestType.Set(&v)
}
// SetRequestTypeNil sets the value for RequestType to be an explicit nil
func (o *Accessrequest) SetRequestTypeNil() {
	o.RequestType.Set(nil)
}

// UnsetRequestType ensures that no value is present for RequestType, not even an explicit nil
func (o *Accessrequest) UnsetRequestType() {
	o.RequestType.Unset()
}

// GetRequestedItems returns the RequestedItems field value
func (o *Accessrequest) GetRequestedItems() []Accessrequestitem {
	if o == nil {
		var ret []Accessrequestitem
		return ret
	}

	return o.RequestedItems
}

// GetRequestedItemsOk returns a tuple with the RequestedItems field value
// and a boolean to check if the value has been set.
func (o *Accessrequest) GetRequestedItemsOk() ([]Accessrequestitem, bool) {
	if o == nil {
		return nil, false
	}
	return o.RequestedItems, true
}

// SetRequestedItems sets field value
func (o *Accessrequest) SetRequestedItems(v []Accessrequestitem) {
	o.RequestedItems = v
}

// GetClientMetadata returns the ClientMetadata field value if set, zero value otherwise.
func (o *Accessrequest) GetClientMetadata() map[string]string {
	if o == nil || IsNil(o.ClientMetadata) {
		var ret map[string]string
		return ret
	}
	return *o.ClientMetadata
}

// GetClientMetadataOk returns a tuple with the ClientMetadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Accessrequest) GetClientMetadataOk() (*map[string]string, bool) {
	if o == nil || IsNil(o.ClientMetadata) {
		return nil, false
	}
	return o.ClientMetadata, true
}

// HasClientMetadata returns a boolean if a field has been set.
func (o *Accessrequest) HasClientMetadata() bool {
	if o != nil && !IsNil(o.ClientMetadata) {
		return true
	}

	return false
}

// SetClientMetadata gets a reference to the given map[string]string and assigns it to the ClientMetadata field.
func (o *Accessrequest) SetClientMetadata(v map[string]string) {
	o.ClientMetadata = &v
}

// GetRequestedForWithRequestedItems returns the RequestedForWithRequestedItems field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Accessrequest) GetRequestedForWithRequestedItems() []Requestedfordtoref {
	if o == nil {
		var ret []Requestedfordtoref
		return ret
	}
	return o.RequestedForWithRequestedItems
}

// GetRequestedForWithRequestedItemsOk returns a tuple with the RequestedForWithRequestedItems field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Accessrequest) GetRequestedForWithRequestedItemsOk() ([]Requestedfordtoref, bool) {
	if o == nil || IsNil(o.RequestedForWithRequestedItems) {
		return nil, false
	}
	return o.RequestedForWithRequestedItems, true
}

// HasRequestedForWithRequestedItems returns a boolean if a field has been set.
func (o *Accessrequest) HasRequestedForWithRequestedItems() bool {
	if o != nil && !IsNil(o.RequestedForWithRequestedItems) {
		return true
	}

	return false
}

// SetRequestedForWithRequestedItems gets a reference to the given []Requestedfordtoref and assigns it to the RequestedForWithRequestedItems field.
func (o *Accessrequest) SetRequestedForWithRequestedItems(v []Requestedfordtoref) {
	o.RequestedForWithRequestedItems = v
}

func (o Accessrequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Accessrequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["requestedFor"] = o.RequestedFor
	if o.RequestType.IsSet() {
		toSerialize["requestType"] = o.RequestType.Get()
	}
	toSerialize["requestedItems"] = o.RequestedItems
	if !IsNil(o.ClientMetadata) {
		toSerialize["clientMetadata"] = o.ClientMetadata
	}
	if o.RequestedForWithRequestedItems != nil {
		toSerialize["requestedForWithRequestedItems"] = o.RequestedForWithRequestedItems
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *Accessrequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"requestedFor",
		"requestedItems",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAccessrequest := _Accessrequest{}

	err = json.Unmarshal(data, &varAccessrequest)

	if err != nil {
		return err
	}

	*o = Accessrequest(varAccessrequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "requestedFor")
		delete(additionalProperties, "requestType")
		delete(additionalProperties, "requestedItems")
		delete(additionalProperties, "clientMetadata")
		delete(additionalProperties, "requestedForWithRequestedItems")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableAccessrequest struct {
	value *Accessrequest
	isSet bool
}

func (v NullableAccessrequest) Get() *Accessrequest {
	return v.value
}

func (v *NullableAccessrequest) Set(val *Accessrequest) {
	v.value = val
	v.isSet = true
}

func (v NullableAccessrequest) IsSet() bool {
	return v.isSet
}

func (v *NullableAccessrequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAccessrequest(val *Accessrequest) *NullableAccessrequest {
	return &NullableAccessrequest{value: val, isSet: true}
}

func (v NullableAccessrequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAccessrequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


