/*
IdentityNow V3 API

Use these APIs to interact with the IdentityNow platform to achieve repeatable, automated processes with greater scalability. We encourage you to join the SailPoint Developer Community forum at https://developer.sailpoint.com/discuss to connect with other developers using our APIs.

API version: 3.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api_v3

import (
	"encoding/json"
	"fmt"
)

// Rule - struct for Rule
type Rule struct {
	GenerateRandomString *GenerateRandomString
	GenericRule *GenericRule
	GetReferenceIdentityAttribute *GetReferenceIdentityAttribute
}

// GenerateRandomStringAsRule is a convenience function that returns GenerateRandomString wrapped in Rule
func GenerateRandomStringAsRule(v *GenerateRandomString) Rule {
	return Rule{
		GenerateRandomString: v,
	}
}

// GenericRuleAsRule is a convenience function that returns GenericRule wrapped in Rule
func GenericRuleAsRule(v *GenericRule) Rule {
	return Rule{
		GenericRule: v,
	}
}

// GetReferenceIdentityAttributeAsRule is a convenience function that returns GetReferenceIdentityAttribute wrapped in Rule
func GetReferenceIdentityAttributeAsRule(v *GetReferenceIdentityAttribute) Rule {
	return Rule{
		GetReferenceIdentityAttribute: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *Rule) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into GenerateRandomString
	err = newStrictDecoder(data).Decode(&dst.GenerateRandomString)
	if err == nil {
		jsonGenerateRandomString, _ := json.Marshal(dst.GenerateRandomString)
		if string(jsonGenerateRandomString) == "{}" { // empty struct
			dst.GenerateRandomString = nil
		} else {
			match++
		}
	} else {
		dst.GenerateRandomString = nil
	}

	// try to unmarshal data into GenericRule
	err = newStrictDecoder(data).Decode(&dst.GenericRule)
	if err == nil {
		jsonGenericRule, _ := json.Marshal(dst.GenericRule)
		if string(jsonGenericRule) == "{}" { // empty struct
			dst.GenericRule = nil
		} else {
			match++
		}
	} else {
		dst.GenericRule = nil
	}

	// try to unmarshal data into GetReferenceIdentityAttribute
	err = newStrictDecoder(data).Decode(&dst.GetReferenceIdentityAttribute)
	if err == nil {
		jsonGetReferenceIdentityAttribute, _ := json.Marshal(dst.GetReferenceIdentityAttribute)
		if string(jsonGetReferenceIdentityAttribute) == "{}" { // empty struct
			dst.GetReferenceIdentityAttribute = nil
		} else {
			match++
		}
	} else {
		dst.GetReferenceIdentityAttribute = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.GenerateRandomString = nil
		dst.GenericRule = nil
		dst.GetReferenceIdentityAttribute = nil

		return fmt.Errorf("data matches more than one schema in oneOf(Rule)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(Rule)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src Rule) MarshalJSON() ([]byte, error) {
	if src.GenerateRandomString != nil {
		return json.Marshal(&src.GenerateRandomString)
	}

	if src.GenericRule != nil {
		return json.Marshal(&src.GenericRule)
	}

	if src.GetReferenceIdentityAttribute != nil {
		return json.Marshal(&src.GetReferenceIdentityAttribute)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *Rule) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.GenerateRandomString != nil {
		return obj.GenerateRandomString
	}

	if obj.GenericRule != nil {
		return obj.GenericRule
	}

	if obj.GetReferenceIdentityAttribute != nil {
		return obj.GetReferenceIdentityAttribute
	}

	// all schemas are nil
	return nil
}

type NullableRule struct {
	value *Rule
	isSet bool
}

func (v NullableRule) Get() *Rule {
	return v.value
}

func (v *NullableRule) Set(val *Rule) {
	v.value = val
	v.isSet = true
}

func (v NullableRule) IsSet() bool {
	return v.isSet
}

func (v *NullableRule) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRule(val *Rule) *NullableRule {
	return &NullableRule{value: val, isSet: true}
}

func (v NullableRule) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRule) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


