/*
IdentityNow V3 API

Use these APIs to interact with the IdentityNow platform to achieve repeatable, automated processes with greater scalability. We encourage you to join the SailPoint Developer Community forum at https://developer.sailpoint.com/discuss to connect with other developers using our APIs.

API version: 3.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api_v3

import (
	"encoding/json"
)

// checks if the LifecyclestateDeleted type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LifecyclestateDeleted{}

// LifecyclestateDeleted Deleted lifecycle state.
type LifecyclestateDeleted struct {
	// Deleted lifecycle state's DTO type.
	Type *string `json:"type,omitempty"`
	// Deleted lifecycle state ID.
	Id *string `json:"id,omitempty"`
	// Deleted lifecycle state's display name.
	Name *string `json:"name,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _LifecyclestateDeleted LifecyclestateDeleted

// NewLifecyclestateDeleted instantiates a new LifecyclestateDeleted object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLifecyclestateDeleted() *LifecyclestateDeleted {
	this := LifecyclestateDeleted{}
	return &this
}

// NewLifecyclestateDeletedWithDefaults instantiates a new LifecyclestateDeleted object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLifecyclestateDeletedWithDefaults() *LifecyclestateDeleted {
	this := LifecyclestateDeleted{}
	return &this
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *LifecyclestateDeleted) GetType() string {
	if o == nil || isNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LifecyclestateDeleted) GetTypeOk() (*string, bool) {
	if o == nil || isNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *LifecyclestateDeleted) HasType() bool {
	if o != nil && !isNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *LifecyclestateDeleted) SetType(v string) {
	o.Type = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *LifecyclestateDeleted) GetId() string {
	if o == nil || isNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LifecyclestateDeleted) GetIdOk() (*string, bool) {
	if o == nil || isNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *LifecyclestateDeleted) HasId() bool {
	if o != nil && !isNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *LifecyclestateDeleted) SetId(v string) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *LifecyclestateDeleted) GetName() string {
	if o == nil || isNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LifecyclestateDeleted) GetNameOk() (*string, bool) {
	if o == nil || isNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *LifecyclestateDeleted) HasName() bool {
	if o != nil && !isNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *LifecyclestateDeleted) SetName(v string) {
	o.Name = &v
}

func (o LifecyclestateDeleted) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LifecyclestateDeleted) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !isNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !isNil(o.Name) {
		toSerialize["name"] = o.Name
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *LifecyclestateDeleted) UnmarshalJSON(bytes []byte) (err error) {
	varLifecyclestateDeleted := _LifecyclestateDeleted{}

	if err = json.Unmarshal(bytes, &varLifecyclestateDeleted); err == nil {
	*o = LifecyclestateDeleted(varLifecyclestateDeleted)
}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {
		delete(additionalProperties, "type")
		delete(additionalProperties, "id")
		delete(additionalProperties, "name")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableLifecyclestateDeleted struct {
	value *LifecyclestateDeleted
	isSet bool
}

func (v NullableLifecyclestateDeleted) Get() *LifecyclestateDeleted {
	return v.value
}

func (v *NullableLifecyclestateDeleted) Set(val *LifecyclestateDeleted) {
	v.value = val
	v.isSet = true
}

func (v NullableLifecyclestateDeleted) IsSet() bool {
	return v.isSet
}

func (v *NullableLifecyclestateDeleted) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLifecyclestateDeleted(val *LifecyclestateDeleted) *NullableLifecyclestateDeleted {
	return &NullableLifecyclestateDeleted{value: val, isSet: true}
}

func (v NullableLifecyclestateDeleted) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLifecyclestateDeleted) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


