/*
Identity Security Cloud API - Access Model Metadata

Use these APIs to interact with the Identity Security Cloud platform to achieve repeatable, automated processes with greater scalability. We encourage you to join the SailPoint Developer Community forum at https://developer.sailpoint.com/discuss to connect with other developers using our APIs.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api_access_model_metadata

import (
	"encoding/json"
	"fmt"
)

// checks if the Innerhit type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Innerhit{}

// Innerhit Inner Hit query object that will cause the specified nested type to be returned as the result matching the supplied query.
type Innerhit struct {
	// The search query using the Elasticsearch [Query String Query](https://www.elastic.co/guide/en/elasticsearch/reference/5.2/query-dsl-query-string-query.html#query-string) syntax from the Query DSL extended by SailPoint to support Nested queries.
	Query string `json:"query"`
	// The nested type to use in the inner hits query.  The nested type [Nested Type](https://www.elastic.co/guide/en/elasticsearch/reference/current/nested.html) refers to a document \"nested\" within another document. For example, an identity can have nested documents for access, accounts, and apps.
	Type string `json:"type"`
	AdditionalProperties map[string]interface{}
}

type _Innerhit Innerhit

// NewInnerhit instantiates a new Innerhit object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInnerhit(query string, type_ string) *Innerhit {
	this := Innerhit{}
	this.Query = query
	this.Type = type_
	return &this
}

// NewInnerhitWithDefaults instantiates a new Innerhit object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInnerhitWithDefaults() *Innerhit {
	this := Innerhit{}
	return &this
}

// GetQuery returns the Query field value
func (o *Innerhit) GetQuery() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Query
}

// GetQueryOk returns a tuple with the Query field value
// and a boolean to check if the value has been set.
func (o *Innerhit) GetQueryOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Query, true
}

// SetQuery sets field value
func (o *Innerhit) SetQuery(v string) {
	o.Query = v
}

// GetType returns the Type field value
func (o *Innerhit) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *Innerhit) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *Innerhit) SetType(v string) {
	o.Type = v
}

func (o Innerhit) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Innerhit) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["query"] = o.Query
	toSerialize["type"] = o.Type

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *Innerhit) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"query",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varInnerhit := _Innerhit{}

	err = json.Unmarshal(data, &varInnerhit)

	if err != nil {
		return err
	}

	*o = Innerhit(varInnerhit)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "query")
		delete(additionalProperties, "type")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableInnerhit struct {
	value *Innerhit
	isSet bool
}

func (v NullableInnerhit) Get() *Innerhit {
	return v.value
}

func (v *NullableInnerhit) Set(val *Innerhit) {
	v.value = val
	v.isSet = true
}

func (v NullableInnerhit) IsSet() bool {
	return v.isSet
}

func (v *NullableInnerhit) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInnerhit(val *Innerhit) *NullableInnerhit {
	return &NullableInnerhit{value: val, isSet: true}
}

func (v NullableInnerhit) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInnerhit) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


