/*
Identity Security Cloud API - Data Access Security

Use these APIs to interact with the Identity Security Cloud platform to achieve repeatable, automated processes with greater scalability. We encourage you to join the SailPoint Developer Community forum at https://developer.sailpoint.com/discuss to connect with other developers using our APIs.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package data_access_security

import (
	"encoding/json"
	"fmt"
)

// checks if the Createdatadictionaryfieldrequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Createdatadictionaryfieldrequest{}

// Createdatadictionaryfieldrequest Request body for creating a custom data dictionary field.
type Createdatadictionaryfieldrequest struct {
	// The unique field name to create.
	Name string `json:"name"`
	// The data dictionary that owns this field.
	DataDictionaryType string `json:"dataDictionaryType"`
	AdditionalProperties map[string]interface{}
}

type _Createdatadictionaryfieldrequest Createdatadictionaryfieldrequest

// NewCreatedatadictionaryfieldrequest instantiates a new Createdatadictionaryfieldrequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreatedatadictionaryfieldrequest(name string, dataDictionaryType string) *Createdatadictionaryfieldrequest {
	this := Createdatadictionaryfieldrequest{}
	this.Name = name
	this.DataDictionaryType = dataDictionaryType
	return &this
}

// NewCreatedatadictionaryfieldrequestWithDefaults instantiates a new Createdatadictionaryfieldrequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreatedatadictionaryfieldrequestWithDefaults() *Createdatadictionaryfieldrequest {
	this := Createdatadictionaryfieldrequest{}
	return &this
}

// GetName returns the Name field value
func (o *Createdatadictionaryfieldrequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *Createdatadictionaryfieldrequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *Createdatadictionaryfieldrequest) SetName(v string) {
	o.Name = v
}

// GetDataDictionaryType returns the DataDictionaryType field value
func (o *Createdatadictionaryfieldrequest) GetDataDictionaryType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DataDictionaryType
}

// GetDataDictionaryTypeOk returns a tuple with the DataDictionaryType field value
// and a boolean to check if the value has been set.
func (o *Createdatadictionaryfieldrequest) GetDataDictionaryTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DataDictionaryType, true
}

// SetDataDictionaryType sets field value
func (o *Createdatadictionaryfieldrequest) SetDataDictionaryType(v string) {
	o.DataDictionaryType = v
}

func (o Createdatadictionaryfieldrequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Createdatadictionaryfieldrequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["dataDictionaryType"] = o.DataDictionaryType

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *Createdatadictionaryfieldrequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"dataDictionaryType",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreatedatadictionaryfieldrequest := _Createdatadictionaryfieldrequest{}

	err = json.Unmarshal(data, &varCreatedatadictionaryfieldrequest)

	if err != nil {
		return err
	}

	*o = Createdatadictionaryfieldrequest(varCreatedatadictionaryfieldrequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "name")
		delete(additionalProperties, "dataDictionaryType")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCreatedatadictionaryfieldrequest struct {
	value *Createdatadictionaryfieldrequest
	isSet bool
}

func (v NullableCreatedatadictionaryfieldrequest) Get() *Createdatadictionaryfieldrequest {
	return v.value
}

func (v *NullableCreatedatadictionaryfieldrequest) Set(val *Createdatadictionaryfieldrequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreatedatadictionaryfieldrequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreatedatadictionaryfieldrequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreatedatadictionaryfieldrequest(val *Createdatadictionaryfieldrequest) *NullableCreatedatadictionaryfieldrequest {
	return &NullableCreatedatadictionaryfieldrequest{value: val, isSet: true}
}

func (v NullableCreatedatadictionaryfieldrequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreatedatadictionaryfieldrequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


