/*
NERM API

The NERM API accesss and modifies resources in your environment.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api_nerm

import (
	"encoding/json"
)

// checks if the Forms type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Forms{}

// Forms struct for Forms
type Forms struct {
	// The user-specified identifier of the form
	Uid *string `json:"uid,omitempty"`
	// The description of the form
	Description *string `json:"description,omitempty"`
	// The name of the form
	Name *string `json:"name,omitempty"`
	// Determines whether the form is archived
	Archived *bool `json:"archived,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _Forms Forms

// NewForms instantiates a new Forms object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewForms() *Forms {
	this := Forms{}
	return &this
}

// NewFormsWithDefaults instantiates a new Forms object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFormsWithDefaults() *Forms {
	this := Forms{}
	return &this
}

// GetUid returns the Uid field value if set, zero value otherwise.
func (o *Forms) GetUid() string {
	if o == nil || IsNil(o.Uid) {
		var ret string
		return ret
	}
	return *o.Uid
}

// GetUidOk returns a tuple with the Uid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Forms) GetUidOk() (*string, bool) {
	if o == nil || IsNil(o.Uid) {
		return nil, false
	}
	return o.Uid, true
}

// HasUid returns a boolean if a field has been set.
func (o *Forms) HasUid() bool {
	if o != nil && !IsNil(o.Uid) {
		return true
	}

	return false
}

// SetUid gets a reference to the given string and assigns it to the Uid field.
func (o *Forms) SetUid(v string) {
	o.Uid = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *Forms) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Forms) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *Forms) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *Forms) SetDescription(v string) {
	o.Description = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *Forms) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Forms) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *Forms) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *Forms) SetName(v string) {
	o.Name = &v
}

// GetArchived returns the Archived field value if set, zero value otherwise.
func (o *Forms) GetArchived() bool {
	if o == nil || IsNil(o.Archived) {
		var ret bool
		return ret
	}
	return *o.Archived
}

// GetArchivedOk returns a tuple with the Archived field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Forms) GetArchivedOk() (*bool, bool) {
	if o == nil || IsNil(o.Archived) {
		return nil, false
	}
	return o.Archived, true
}

// HasArchived returns a boolean if a field has been set.
func (o *Forms) HasArchived() bool {
	if o != nil && !IsNil(o.Archived) {
		return true
	}

	return false
}

// SetArchived gets a reference to the given bool and assigns it to the Archived field.
func (o *Forms) SetArchived(v bool) {
	o.Archived = &v
}

func (o Forms) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Forms) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Uid) {
		toSerialize["uid"] = o.Uid
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Archived) {
		toSerialize["archived"] = o.Archived
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *Forms) UnmarshalJSON(data []byte) (err error) {
	varForms := _Forms{}

	err = json.Unmarshal(data, &varForms)

	if err != nil {
		return err
	}

	*o = Forms(varForms)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "uid")
		delete(additionalProperties, "description")
		delete(additionalProperties, "name")
		delete(additionalProperties, "archived")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableForms struct {
	value *Forms
	isSet bool
}

func (v NullableForms) Get() *Forms {
	return v.value
}

func (v *NullableForms) Set(val *Forms) {
	v.value = val
	v.isSet = true
}

func (v NullableForms) IsSet() bool {
	return v.isSet
}

func (v *NullableForms) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableForms(val *Forms) *NullableForms {
	return &NullableForms{value: val, isSet: true}
}

func (v NullableForms) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableForms) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


