/*
NERM API

The NERM API accesss and modifies resources in your environment.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api_nerm

import (
	"encoding/json"
)

// checks if the UserProfile1 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UserProfile1{}

// UserProfile1 struct for UserProfile1
type UserProfile1 struct {
	UserId *string `json:"user_id,omitempty"`
	ProfileId *string `json:"profile_id,omitempty"`
	NeAttributeId *string `json:"ne_attribute_id,omitempty"`
	RelationshipType *string `json:"relationship_type,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _UserProfile1 UserProfile1

// NewUserProfile1 instantiates a new UserProfile1 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUserProfile1() *UserProfile1 {
	this := UserProfile1{}
	return &this
}

// NewUserProfile1WithDefaults instantiates a new UserProfile1 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserProfile1WithDefaults() *UserProfile1 {
	this := UserProfile1{}
	return &this
}

// GetUserId returns the UserId field value if set, zero value otherwise.
func (o *UserProfile1) GetUserId() string {
	if o == nil || IsNil(o.UserId) {
		var ret string
		return ret
	}
	return *o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserProfile1) GetUserIdOk() (*string, bool) {
	if o == nil || IsNil(o.UserId) {
		return nil, false
	}
	return o.UserId, true
}

// HasUserId returns a boolean if a field has been set.
func (o *UserProfile1) HasUserId() bool {
	if o != nil && !IsNil(o.UserId) {
		return true
	}

	return false
}

// SetUserId gets a reference to the given string and assigns it to the UserId field.
func (o *UserProfile1) SetUserId(v string) {
	o.UserId = &v
}

// GetProfileId returns the ProfileId field value if set, zero value otherwise.
func (o *UserProfile1) GetProfileId() string {
	if o == nil || IsNil(o.ProfileId) {
		var ret string
		return ret
	}
	return *o.ProfileId
}

// GetProfileIdOk returns a tuple with the ProfileId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserProfile1) GetProfileIdOk() (*string, bool) {
	if o == nil || IsNil(o.ProfileId) {
		return nil, false
	}
	return o.ProfileId, true
}

// HasProfileId returns a boolean if a field has been set.
func (o *UserProfile1) HasProfileId() bool {
	if o != nil && !IsNil(o.ProfileId) {
		return true
	}

	return false
}

// SetProfileId gets a reference to the given string and assigns it to the ProfileId field.
func (o *UserProfile1) SetProfileId(v string) {
	o.ProfileId = &v
}

// GetNeAttributeId returns the NeAttributeId field value if set, zero value otherwise.
func (o *UserProfile1) GetNeAttributeId() string {
	if o == nil || IsNil(o.NeAttributeId) {
		var ret string
		return ret
	}
	return *o.NeAttributeId
}

// GetNeAttributeIdOk returns a tuple with the NeAttributeId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserProfile1) GetNeAttributeIdOk() (*string, bool) {
	if o == nil || IsNil(o.NeAttributeId) {
		return nil, false
	}
	return o.NeAttributeId, true
}

// HasNeAttributeId returns a boolean if a field has been set.
func (o *UserProfile1) HasNeAttributeId() bool {
	if o != nil && !IsNil(o.NeAttributeId) {
		return true
	}

	return false
}

// SetNeAttributeId gets a reference to the given string and assigns it to the NeAttributeId field.
func (o *UserProfile1) SetNeAttributeId(v string) {
	o.NeAttributeId = &v
}

// GetRelationshipType returns the RelationshipType field value if set, zero value otherwise.
func (o *UserProfile1) GetRelationshipType() string {
	if o == nil || IsNil(o.RelationshipType) {
		var ret string
		return ret
	}
	return *o.RelationshipType
}

// GetRelationshipTypeOk returns a tuple with the RelationshipType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserProfile1) GetRelationshipTypeOk() (*string, bool) {
	if o == nil || IsNil(o.RelationshipType) {
		return nil, false
	}
	return o.RelationshipType, true
}

// HasRelationshipType returns a boolean if a field has been set.
func (o *UserProfile1) HasRelationshipType() bool {
	if o != nil && !IsNil(o.RelationshipType) {
		return true
	}

	return false
}

// SetRelationshipType gets a reference to the given string and assigns it to the RelationshipType field.
func (o *UserProfile1) SetRelationshipType(v string) {
	o.RelationshipType = &v
}

func (o UserProfile1) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UserProfile1) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.UserId) {
		toSerialize["user_id"] = o.UserId
	}
	if !IsNil(o.ProfileId) {
		toSerialize["profile_id"] = o.ProfileId
	}
	if !IsNil(o.NeAttributeId) {
		toSerialize["ne_attribute_id"] = o.NeAttributeId
	}
	if !IsNil(o.RelationshipType) {
		toSerialize["relationship_type"] = o.RelationshipType
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *UserProfile1) UnmarshalJSON(data []byte) (err error) {
	varUserProfile1 := _UserProfile1{}

	err = json.Unmarshal(data, &varUserProfile1)

	if err != nil {
		return err
	}

	*o = UserProfile1(varUserProfile1)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "user_id")
		delete(additionalProperties, "profile_id")
		delete(additionalProperties, "ne_attribute_id")
		delete(additionalProperties, "relationship_type")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableUserProfile1 struct {
	value *UserProfile1
	isSet bool
}

func (v NullableUserProfile1) Get() *UserProfile1 {
	return v.value
}

func (v *NullableUserProfile1) Set(val *UserProfile1) {
	v.value = val
	v.isSet = true
}

func (v NullableUserProfile1) IsSet() bool {
	return v.isSet
}

func (v *NullableUserProfile1) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserProfile1(val *UserProfile1) *NullableUserProfile1 {
	return &NullableUserProfile1{value: val, isSet: true}
}

func (v NullableUserProfile1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserProfile1) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


