/*
Identity Security Cloud API - Entitlements

Use these APIs to interact with the Identity Security Cloud platform to achieve repeatable, automated processes with greater scalability. We encourage you to join the SailPoint Developer Community forum at https://developer.sailpoint.com/discuss to connect with other developers using our APIs.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api_entitlements

import (
	"encoding/json"
)

// checks if the Entitlementrequestconfig type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Entitlementrequestconfig{}

// Entitlementrequestconfig struct for Entitlementrequestconfig
type Entitlementrequestconfig struct {
	AccessRequestConfig *Entitlementaccessrequestconfig `json:"accessRequestConfig,omitempty"`
	RevocationRequestConfig *Entitlementrevocationrequestconfig `json:"revocationRequestConfig,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _Entitlementrequestconfig Entitlementrequestconfig

// NewEntitlementrequestconfig instantiates a new Entitlementrequestconfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEntitlementrequestconfig() *Entitlementrequestconfig {
	this := Entitlementrequestconfig{}
	return &this
}

// NewEntitlementrequestconfigWithDefaults instantiates a new Entitlementrequestconfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEntitlementrequestconfigWithDefaults() *Entitlementrequestconfig {
	this := Entitlementrequestconfig{}
	return &this
}

// GetAccessRequestConfig returns the AccessRequestConfig field value if set, zero value otherwise.
func (o *Entitlementrequestconfig) GetAccessRequestConfig() Entitlementaccessrequestconfig {
	if o == nil || IsNil(o.AccessRequestConfig) {
		var ret Entitlementaccessrequestconfig
		return ret
	}
	return *o.AccessRequestConfig
}

// GetAccessRequestConfigOk returns a tuple with the AccessRequestConfig field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Entitlementrequestconfig) GetAccessRequestConfigOk() (*Entitlementaccessrequestconfig, bool) {
	if o == nil || IsNil(o.AccessRequestConfig) {
		return nil, false
	}
	return o.AccessRequestConfig, true
}

// HasAccessRequestConfig returns a boolean if a field has been set.
func (o *Entitlementrequestconfig) HasAccessRequestConfig() bool {
	if o != nil && !IsNil(o.AccessRequestConfig) {
		return true
	}

	return false
}

// SetAccessRequestConfig gets a reference to the given Entitlementaccessrequestconfig and assigns it to the AccessRequestConfig field.
func (o *Entitlementrequestconfig) SetAccessRequestConfig(v Entitlementaccessrequestconfig) {
	o.AccessRequestConfig = &v
}

// GetRevocationRequestConfig returns the RevocationRequestConfig field value if set, zero value otherwise.
func (o *Entitlementrequestconfig) GetRevocationRequestConfig() Entitlementrevocationrequestconfig {
	if o == nil || IsNil(o.RevocationRequestConfig) {
		var ret Entitlementrevocationrequestconfig
		return ret
	}
	return *o.RevocationRequestConfig
}

// GetRevocationRequestConfigOk returns a tuple with the RevocationRequestConfig field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Entitlementrequestconfig) GetRevocationRequestConfigOk() (*Entitlementrevocationrequestconfig, bool) {
	if o == nil || IsNil(o.RevocationRequestConfig) {
		return nil, false
	}
	return o.RevocationRequestConfig, true
}

// HasRevocationRequestConfig returns a boolean if a field has been set.
func (o *Entitlementrequestconfig) HasRevocationRequestConfig() bool {
	if o != nil && !IsNil(o.RevocationRequestConfig) {
		return true
	}

	return false
}

// SetRevocationRequestConfig gets a reference to the given Entitlementrevocationrequestconfig and assigns it to the RevocationRequestConfig field.
func (o *Entitlementrequestconfig) SetRevocationRequestConfig(v Entitlementrevocationrequestconfig) {
	o.RevocationRequestConfig = &v
}

func (o Entitlementrequestconfig) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Entitlementrequestconfig) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AccessRequestConfig) {
		toSerialize["accessRequestConfig"] = o.AccessRequestConfig
	}
	if !IsNil(o.RevocationRequestConfig) {
		toSerialize["revocationRequestConfig"] = o.RevocationRequestConfig
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *Entitlementrequestconfig) UnmarshalJSON(data []byte) (err error) {
	varEntitlementrequestconfig := _Entitlementrequestconfig{}

	err = json.Unmarshal(data, &varEntitlementrequestconfig)

	if err != nil {
		return err
	}

	*o = Entitlementrequestconfig(varEntitlementrequestconfig)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "accessRequestConfig")
		delete(additionalProperties, "revocationRequestConfig")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableEntitlementrequestconfig struct {
	value *Entitlementrequestconfig
	isSet bool
}

func (v NullableEntitlementrequestconfig) Get() *Entitlementrequestconfig {
	return v.value
}

func (v *NullableEntitlementrequestconfig) Set(val *Entitlementrequestconfig) {
	v.value = val
	v.isSet = true
}

func (v NullableEntitlementrequestconfig) IsSet() bool {
	return v.isSet
}

func (v *NullableEntitlementrequestconfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEntitlementrequestconfig(val *Entitlementrequestconfig) *NullableEntitlementrequestconfig {
	return &NullableEntitlementrequestconfig{value: val, isSet: true}
}

func (v NullableEntitlementrequestconfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEntitlementrequestconfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


