/*
Identity Security Cloud API - Certification Summaries

Use these APIs to interact with the Identity Security Cloud platform to achieve repeatable, automated processes with greater scalability. We encourage you to join the SailPoint Developer Community forum at https://developer.sailpoint.com/discuss to connect with other developers using our APIs.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api_certification_summaries

import (
	"encoding/json"
)

// checks if the DataaccessCategoriesInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DataaccessCategoriesInner{}

// DataaccessCategoriesInner struct for DataaccessCategoriesInner
type DataaccessCategoriesInner struct {
	// Value of the category
	Value *string `json:"value,omitempty"`
	// Number of matched for each category
	MatchCount *int32 `json:"matchCount,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _DataaccessCategoriesInner DataaccessCategoriesInner

// NewDataaccessCategoriesInner instantiates a new DataaccessCategoriesInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDataaccessCategoriesInner() *DataaccessCategoriesInner {
	this := DataaccessCategoriesInner{}
	return &this
}

// NewDataaccessCategoriesInnerWithDefaults instantiates a new DataaccessCategoriesInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDataaccessCategoriesInnerWithDefaults() *DataaccessCategoriesInner {
	this := DataaccessCategoriesInner{}
	return &this
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *DataaccessCategoriesInner) GetValue() string {
	if o == nil || IsNil(o.Value) {
		var ret string
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DataaccessCategoriesInner) GetValueOk() (*string, bool) {
	if o == nil || IsNil(o.Value) {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *DataaccessCategoriesInner) HasValue() bool {
	if o != nil && !IsNil(o.Value) {
		return true
	}

	return false
}

// SetValue gets a reference to the given string and assigns it to the Value field.
func (o *DataaccessCategoriesInner) SetValue(v string) {
	o.Value = &v
}

// GetMatchCount returns the MatchCount field value if set, zero value otherwise.
func (o *DataaccessCategoriesInner) GetMatchCount() int32 {
	if o == nil || IsNil(o.MatchCount) {
		var ret int32
		return ret
	}
	return *o.MatchCount
}

// GetMatchCountOk returns a tuple with the MatchCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DataaccessCategoriesInner) GetMatchCountOk() (*int32, bool) {
	if o == nil || IsNil(o.MatchCount) {
		return nil, false
	}
	return o.MatchCount, true
}

// HasMatchCount returns a boolean if a field has been set.
func (o *DataaccessCategoriesInner) HasMatchCount() bool {
	if o != nil && !IsNil(o.MatchCount) {
		return true
	}

	return false
}

// SetMatchCount gets a reference to the given int32 and assigns it to the MatchCount field.
func (o *DataaccessCategoriesInner) SetMatchCount(v int32) {
	o.MatchCount = &v
}

func (o DataaccessCategoriesInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DataaccessCategoriesInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Value) {
		toSerialize["value"] = o.Value
	}
	if !IsNil(o.MatchCount) {
		toSerialize["matchCount"] = o.MatchCount
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *DataaccessCategoriesInner) UnmarshalJSON(data []byte) (err error) {
	varDataaccessCategoriesInner := _DataaccessCategoriesInner{}

	err = json.Unmarshal(data, &varDataaccessCategoriesInner)

	if err != nil {
		return err
	}

	*o = DataaccessCategoriesInner(varDataaccessCategoriesInner)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "value")
		delete(additionalProperties, "matchCount")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableDataaccessCategoriesInner struct {
	value *DataaccessCategoriesInner
	isSet bool
}

func (v NullableDataaccessCategoriesInner) Get() *DataaccessCategoriesInner {
	return v.value
}

func (v *NullableDataaccessCategoriesInner) Set(val *DataaccessCategoriesInner) {
	v.value = val
	v.isSet = true
}

func (v NullableDataaccessCategoriesInner) IsSet() bool {
	return v.isSet
}

func (v *NullableDataaccessCategoriesInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDataaccessCategoriesInner(val *DataaccessCategoriesInner) *NullableDataaccessCategoriesInner {
	return &NullableDataaccessCategoriesInner{value: val, isSet: true}
}

func (v NullableDataaccessCategoriesInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDataaccessCategoriesInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


