/*
Identity Security Cloud API - Sources

Use these APIs to interact with the Identity Security Cloud platform to achieve repeatable, automated processes with greater scalability. We encourage you to join the SailPoint Developer Community forum at https://developer.sailpoint.com/discuss to connect with other developers using our APIs.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sources

import (
	"encoding/json"
)

// checks if the LoadaccountstaskTaskAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LoadaccountstaskTaskAttributes{}

// LoadaccountstaskTaskAttributes Extra attributes map(dictionary) for the task.
type LoadaccountstaskTaskAttributes struct {
	// The id of the source
	AppId *string `json:"appId,omitempty"`
	// The indicator if the aggregation process was enabled/disabled for the aggregation job
	OptimizedAggregation *string `json:"optimizedAggregation,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _LoadaccountstaskTaskAttributes LoadaccountstaskTaskAttributes

// NewLoadaccountstaskTaskAttributes instantiates a new LoadaccountstaskTaskAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLoadaccountstaskTaskAttributes() *LoadaccountstaskTaskAttributes {
	this := LoadaccountstaskTaskAttributes{}
	return &this
}

// NewLoadaccountstaskTaskAttributesWithDefaults instantiates a new LoadaccountstaskTaskAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLoadaccountstaskTaskAttributesWithDefaults() *LoadaccountstaskTaskAttributes {
	this := LoadaccountstaskTaskAttributes{}
	return &this
}

// GetAppId returns the AppId field value if set, zero value otherwise.
func (o *LoadaccountstaskTaskAttributes) GetAppId() string {
	if o == nil || IsNil(o.AppId) {
		var ret string
		return ret
	}
	return *o.AppId
}

// GetAppIdOk returns a tuple with the AppId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LoadaccountstaskTaskAttributes) GetAppIdOk() (*string, bool) {
	if o == nil || IsNil(o.AppId) {
		return nil, false
	}
	return o.AppId, true
}

// HasAppId returns a boolean if a field has been set.
func (o *LoadaccountstaskTaskAttributes) HasAppId() bool {
	if o != nil && !IsNil(o.AppId) {
		return true
	}

	return false
}

// SetAppId gets a reference to the given string and assigns it to the AppId field.
func (o *LoadaccountstaskTaskAttributes) SetAppId(v string) {
	o.AppId = &v
}

// GetOptimizedAggregation returns the OptimizedAggregation field value if set, zero value otherwise.
func (o *LoadaccountstaskTaskAttributes) GetOptimizedAggregation() string {
	if o == nil || IsNil(o.OptimizedAggregation) {
		var ret string
		return ret
	}
	return *o.OptimizedAggregation
}

// GetOptimizedAggregationOk returns a tuple with the OptimizedAggregation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LoadaccountstaskTaskAttributes) GetOptimizedAggregationOk() (*string, bool) {
	if o == nil || IsNil(o.OptimizedAggregation) {
		return nil, false
	}
	return o.OptimizedAggregation, true
}

// HasOptimizedAggregation returns a boolean if a field has been set.
func (o *LoadaccountstaskTaskAttributes) HasOptimizedAggregation() bool {
	if o != nil && !IsNil(o.OptimizedAggregation) {
		return true
	}

	return false
}

// SetOptimizedAggregation gets a reference to the given string and assigns it to the OptimizedAggregation field.
func (o *LoadaccountstaskTaskAttributes) SetOptimizedAggregation(v string) {
	o.OptimizedAggregation = &v
}

func (o LoadaccountstaskTaskAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LoadaccountstaskTaskAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AppId) {
		toSerialize["appId"] = o.AppId
	}
	if !IsNil(o.OptimizedAggregation) {
		toSerialize["optimizedAggregation"] = o.OptimizedAggregation
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *LoadaccountstaskTaskAttributes) UnmarshalJSON(data []byte) (err error) {
	varLoadaccountstaskTaskAttributes := _LoadaccountstaskTaskAttributes{}

	err = json.Unmarshal(data, &varLoadaccountstaskTaskAttributes)

	if err != nil {
		return err
	}

	*o = LoadaccountstaskTaskAttributes(varLoadaccountstaskTaskAttributes)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "appId")
		delete(additionalProperties, "optimizedAggregation")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableLoadaccountstaskTaskAttributes struct {
	value *LoadaccountstaskTaskAttributes
	isSet bool
}

func (v NullableLoadaccountstaskTaskAttributes) Get() *LoadaccountstaskTaskAttributes {
	return v.value
}

func (v *NullableLoadaccountstaskTaskAttributes) Set(val *LoadaccountstaskTaskAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableLoadaccountstaskTaskAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableLoadaccountstaskTaskAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLoadaccountstaskTaskAttributes(val *LoadaccountstaskTaskAttributes) *NullableLoadaccountstaskTaskAttributes {
	return &NullableLoadaccountstaskTaskAttributes{value: val, isSet: true}
}

func (v NullableLoadaccountstaskTaskAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLoadaccountstaskTaskAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


