/*
Identity Security Cloud API - Suggested Entitlement Description

Use these APIs to interact with the Identity Security Cloud platform to achieve repeatable, automated processes with greater scalability. We encourage you to join the SailPoint Developer Community forum at https://developer.sailpoint.com/discuss to connect with other developers using our APIs.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api_suggested_entitlement_description_v1

import (
	"encoding/json"
)

// checks if the CreateAutoWriteSettingsV1409Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateAutoWriteSettingsV1409Response{}

// CreateAutoWriteSettingsV1409Response struct for CreateAutoWriteSettingsV1409Response
type CreateAutoWriteSettingsV1409Response struct {
	// A message describing the error
	ErrorName interface{} `json:"errorName,omitempty"`
	// Description of the error
	ErrorMessage interface{} `json:"errorMessage,omitempty"`
	// Unique tracking id for the error.
	TrackingId *string `json:"trackingId,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _CreateAutoWriteSettingsV1409Response CreateAutoWriteSettingsV1409Response

// NewCreateAutoWriteSettingsV1409Response instantiates a new CreateAutoWriteSettingsV1409Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateAutoWriteSettingsV1409Response() *CreateAutoWriteSettingsV1409Response {
	this := CreateAutoWriteSettingsV1409Response{}
	return &this
}

// NewCreateAutoWriteSettingsV1409ResponseWithDefaults instantiates a new CreateAutoWriteSettingsV1409Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateAutoWriteSettingsV1409ResponseWithDefaults() *CreateAutoWriteSettingsV1409Response {
	this := CreateAutoWriteSettingsV1409Response{}
	return &this
}

// GetErrorName returns the ErrorName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateAutoWriteSettingsV1409Response) GetErrorName() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.ErrorName
}

// GetErrorNameOk returns a tuple with the ErrorName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateAutoWriteSettingsV1409Response) GetErrorNameOk() (*interface{}, bool) {
	if o == nil || IsNil(o.ErrorName) {
		return nil, false
	}
	return &o.ErrorName, true
}

// HasErrorName returns a boolean if a field has been set.
func (o *CreateAutoWriteSettingsV1409Response) HasErrorName() bool {
	if o != nil && !IsNil(o.ErrorName) {
		return true
	}

	return false
}

// SetErrorName gets a reference to the given interface{} and assigns it to the ErrorName field.
func (o *CreateAutoWriteSettingsV1409Response) SetErrorName(v interface{}) {
	o.ErrorName = v
}

// GetErrorMessage returns the ErrorMessage field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateAutoWriteSettingsV1409Response) GetErrorMessage() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.ErrorMessage
}

// GetErrorMessageOk returns a tuple with the ErrorMessage field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateAutoWriteSettingsV1409Response) GetErrorMessageOk() (*interface{}, bool) {
	if o == nil || IsNil(o.ErrorMessage) {
		return nil, false
	}
	return &o.ErrorMessage, true
}

// HasErrorMessage returns a boolean if a field has been set.
func (o *CreateAutoWriteSettingsV1409Response) HasErrorMessage() bool {
	if o != nil && !IsNil(o.ErrorMessage) {
		return true
	}

	return false
}

// SetErrorMessage gets a reference to the given interface{} and assigns it to the ErrorMessage field.
func (o *CreateAutoWriteSettingsV1409Response) SetErrorMessage(v interface{}) {
	o.ErrorMessage = v
}

// GetTrackingId returns the TrackingId field value if set, zero value otherwise.
func (o *CreateAutoWriteSettingsV1409Response) GetTrackingId() string {
	if o == nil || IsNil(o.TrackingId) {
		var ret string
		return ret
	}
	return *o.TrackingId
}

// GetTrackingIdOk returns a tuple with the TrackingId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateAutoWriteSettingsV1409Response) GetTrackingIdOk() (*string, bool) {
	if o == nil || IsNil(o.TrackingId) {
		return nil, false
	}
	return o.TrackingId, true
}

// HasTrackingId returns a boolean if a field has been set.
func (o *CreateAutoWriteSettingsV1409Response) HasTrackingId() bool {
	if o != nil && !IsNil(o.TrackingId) {
		return true
	}

	return false
}

// SetTrackingId gets a reference to the given string and assigns it to the TrackingId field.
func (o *CreateAutoWriteSettingsV1409Response) SetTrackingId(v string) {
	o.TrackingId = &v
}

func (o CreateAutoWriteSettingsV1409Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateAutoWriteSettingsV1409Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.ErrorName != nil {
		toSerialize["errorName"] = o.ErrorName
	}
	if o.ErrorMessage != nil {
		toSerialize["errorMessage"] = o.ErrorMessage
	}
	if !IsNil(o.TrackingId) {
		toSerialize["trackingId"] = o.TrackingId
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CreateAutoWriteSettingsV1409Response) UnmarshalJSON(data []byte) (err error) {
	varCreateAutoWriteSettingsV1409Response := _CreateAutoWriteSettingsV1409Response{}

	err = json.Unmarshal(data, &varCreateAutoWriteSettingsV1409Response)

	if err != nil {
		return err
	}

	*o = CreateAutoWriteSettingsV1409Response(varCreateAutoWriteSettingsV1409Response)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "errorName")
		delete(additionalProperties, "errorMessage")
		delete(additionalProperties, "trackingId")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCreateAutoWriteSettingsV1409Response struct {
	value *CreateAutoWriteSettingsV1409Response
	isSet bool
}

func (v NullableCreateAutoWriteSettingsV1409Response) Get() *CreateAutoWriteSettingsV1409Response {
	return v.value
}

func (v *NullableCreateAutoWriteSettingsV1409Response) Set(val *CreateAutoWriteSettingsV1409Response) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateAutoWriteSettingsV1409Response) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateAutoWriteSettingsV1409Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateAutoWriteSettingsV1409Response(val *CreateAutoWriteSettingsV1409Response) *NullableCreateAutoWriteSettingsV1409Response {
	return &NullableCreateAutoWriteSettingsV1409Response{value: val, isSet: true}
}

func (v NullableCreateAutoWriteSettingsV1409Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateAutoWriteSettingsV1409Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


