/*
Identity Security Cloud API - Privilege Criteria

Testing PrivilegeCriteriaAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package privilege_criteria

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/sailpoint-oss/golang-sdk/v3/privilege_criteria"
)

func Test_privilege_criteria_PrivilegeCriteriaAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test PrivilegeCriteriaAPIService CreateCustomPrivilegeCriteriaV1", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.PrivilegeCriteriaAPI.CreateCustomPrivilegeCriteriaV1(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PrivilegeCriteriaAPIService DeleteCustomPrivilegeCriteriaV1", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var criteriaId string

		httpRes, err := apiClient.PrivilegeCriteriaAPI.DeleteCustomPrivilegeCriteriaV1(context.Background(), criteriaId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PrivilegeCriteriaAPIService GetPrivilegeCriteriaV1", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var criteriaId string

		resp, httpRes, err := apiClient.PrivilegeCriteriaAPI.GetPrivilegeCriteriaV1(context.Background(), criteriaId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PrivilegeCriteriaAPIService ListPrivilegeCriteriaV1", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.PrivilegeCriteriaAPI.ListPrivilegeCriteriaV1(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PrivilegeCriteriaAPIService PutCustomPrivilegeCriteriaValueV1", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var criteriaId string

		resp, httpRes, err := apiClient.PrivilegeCriteriaAPI.PutCustomPrivilegeCriteriaValueV1(context.Background(), criteriaId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
