/*
Identity Security Cloud API - SP-Config

Use these APIs to interact with the Identity Security Cloud platform to achieve repeatable, automated processes with greater scalability. We encourage you to join the SailPoint Developer Community forum at https://developer.sailpoint.com/discuss to connect with other developers using our APIs.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api_sp_config_v1

import (
	"encoding/json"
)

// checks if the Configobject type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Configobject{}

// Configobject Config export and import format for individual object configurations.
type Configobject struct {
	// Current version of configuration object.
	Version *int32 `json:"version,omitempty"`
	Self *Selfimportexportdto `json:"self,omitempty"`
	// Object details. Format dependant on the object type.
	Object map[string]interface{} `json:"object,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _Configobject Configobject

// NewConfigobject instantiates a new Configobject object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConfigobject() *Configobject {
	this := Configobject{}
	return &this
}

// NewConfigobjectWithDefaults instantiates a new Configobject object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConfigobjectWithDefaults() *Configobject {
	this := Configobject{}
	return &this
}

// GetVersion returns the Version field value if set, zero value otherwise.
func (o *Configobject) GetVersion() int32 {
	if o == nil || IsNil(o.Version) {
		var ret int32
		return ret
	}
	return *o.Version
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Configobject) GetVersionOk() (*int32, bool) {
	if o == nil || IsNil(o.Version) {
		return nil, false
	}
	return o.Version, true
}

// HasVersion returns a boolean if a field has been set.
func (o *Configobject) HasVersion() bool {
	if o != nil && !IsNil(o.Version) {
		return true
	}

	return false
}

// SetVersion gets a reference to the given int32 and assigns it to the Version field.
func (o *Configobject) SetVersion(v int32) {
	o.Version = &v
}

// GetSelf returns the Self field value if set, zero value otherwise.
func (o *Configobject) GetSelf() Selfimportexportdto {
	if o == nil || IsNil(o.Self) {
		var ret Selfimportexportdto
		return ret
	}
	return *o.Self
}

// GetSelfOk returns a tuple with the Self field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Configobject) GetSelfOk() (*Selfimportexportdto, bool) {
	if o == nil || IsNil(o.Self) {
		return nil, false
	}
	return o.Self, true
}

// HasSelf returns a boolean if a field has been set.
func (o *Configobject) HasSelf() bool {
	if o != nil && !IsNil(o.Self) {
		return true
	}

	return false
}

// SetSelf gets a reference to the given Selfimportexportdto and assigns it to the Self field.
func (o *Configobject) SetSelf(v Selfimportexportdto) {
	o.Self = &v
}

// GetObject returns the Object field value if set, zero value otherwise.
func (o *Configobject) GetObject() map[string]interface{} {
	if o == nil || IsNil(o.Object) {
		var ret map[string]interface{}
		return ret
	}
	return o.Object
}

// GetObjectOk returns a tuple with the Object field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Configobject) GetObjectOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Object) {
		return map[string]interface{}{}, false
	}
	return o.Object, true
}

// HasObject returns a boolean if a field has been set.
func (o *Configobject) HasObject() bool {
	if o != nil && !IsNil(o.Object) {
		return true
	}

	return false
}

// SetObject gets a reference to the given map[string]interface{} and assigns it to the Object field.
func (o *Configobject) SetObject(v map[string]interface{}) {
	o.Object = v
}

func (o Configobject) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Configobject) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Version) {
		toSerialize["version"] = o.Version
	}
	if !IsNil(o.Self) {
		toSerialize["self"] = o.Self
	}
	if !IsNil(o.Object) {
		toSerialize["object"] = o.Object
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *Configobject) UnmarshalJSON(data []byte) (err error) {
	varConfigobject := _Configobject{}

	err = json.Unmarshal(data, &varConfigobject)

	if err != nil {
		return err
	}

	*o = Configobject(varConfigobject)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "version")
		delete(additionalProperties, "self")
		delete(additionalProperties, "object")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableConfigobject struct {
	value *Configobject
	isSet bool
}

func (v NullableConfigobject) Get() *Configobject {
	return v.value
}

func (v *NullableConfigobject) Set(val *Configobject) {
	v.value = val
	v.isSet = true
}

func (v NullableConfigobject) IsSet() bool {
	return v.isSet
}

func (v *NullableConfigobject) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConfigobject(val *Configobject) *NullableConfigobject {
	return &NullableConfigobject{value: val, isSet: true}
}

func (v NullableConfigobject) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConfigobject) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


