/*
Identity Security Cloud API - Connector Rule Management

Use these APIs to interact with the Identity Security Cloud platform to achieve repeatable, automated processes with greater scalability. We encourage you to join the SailPoint Developer Community forum at https://developer.sailpoint.com/discuss to connect with other developers using our APIs.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api_connector_rule_management

import (
	"encoding/json"
	"fmt"
)

// checks if the Connectorruleresponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Connectorruleresponse{}

// Connectorruleresponse ConnectorRuleResponse
type Connectorruleresponse struct {
	// the name of the rule
	Name string `json:"name"`
	// a description of the rule's purpose
	Description NullableString `json:"description,omitempty"`
	// the type of rule
	Type string `json:"type"`
	Signature *ConnectorrulecreaterequestSignature `json:"signature,omitempty"`
	SourceCode Sourcecode `json:"sourceCode"`
	// a map of string to objects
	Attributes map[string]interface{} `json:"attributes,omitempty"`
	// the ID of the rule
	Id string `json:"id"`
	// an ISO 8601 UTC timestamp when this rule was created
	Created string `json:"created"`
	// an ISO 8601 UTC timestamp when this rule was last modified
	Modified NullableString `json:"modified,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _Connectorruleresponse Connectorruleresponse

// NewConnectorruleresponse instantiates a new Connectorruleresponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConnectorruleresponse(name string, type_ string, sourceCode Sourcecode, id string, created string) *Connectorruleresponse {
	this := Connectorruleresponse{}
	this.Name = name
	this.Type = type_
	this.SourceCode = sourceCode
	this.Id = id
	this.Created = created
	return &this
}

// NewConnectorruleresponseWithDefaults instantiates a new Connectorruleresponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConnectorruleresponseWithDefaults() *Connectorruleresponse {
	this := Connectorruleresponse{}
	return &this
}

// GetName returns the Name field value
func (o *Connectorruleresponse) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *Connectorruleresponse) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *Connectorruleresponse) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Connectorruleresponse) GetDescription() string {
	if o == nil || IsNil(o.Description.Get()) {
		var ret string
		return ret
	}
	return *o.Description.Get()
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Connectorruleresponse) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Description.Get(), o.Description.IsSet()
}

// HasDescription returns a boolean if a field has been set.
func (o *Connectorruleresponse) HasDescription() bool {
	if o != nil && o.Description.IsSet() {
		return true
	}

	return false
}

// SetDescription gets a reference to the given NullableString and assigns it to the Description field.
func (o *Connectorruleresponse) SetDescription(v string) {
	o.Description.Set(&v)
}
// SetDescriptionNil sets the value for Description to be an explicit nil
func (o *Connectorruleresponse) SetDescriptionNil() {
	o.Description.Set(nil)
}

// UnsetDescription ensures that no value is present for Description, not even an explicit nil
func (o *Connectorruleresponse) UnsetDescription() {
	o.Description.Unset()
}

// GetType returns the Type field value
func (o *Connectorruleresponse) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *Connectorruleresponse) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *Connectorruleresponse) SetType(v string) {
	o.Type = v
}

// GetSignature returns the Signature field value if set, zero value otherwise.
func (o *Connectorruleresponse) GetSignature() ConnectorrulecreaterequestSignature {
	if o == nil || IsNil(o.Signature) {
		var ret ConnectorrulecreaterequestSignature
		return ret
	}
	return *o.Signature
}

// GetSignatureOk returns a tuple with the Signature field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Connectorruleresponse) GetSignatureOk() (*ConnectorrulecreaterequestSignature, bool) {
	if o == nil || IsNil(o.Signature) {
		return nil, false
	}
	return o.Signature, true
}

// HasSignature returns a boolean if a field has been set.
func (o *Connectorruleresponse) HasSignature() bool {
	if o != nil && !IsNil(o.Signature) {
		return true
	}

	return false
}

// SetSignature gets a reference to the given ConnectorrulecreaterequestSignature and assigns it to the Signature field.
func (o *Connectorruleresponse) SetSignature(v ConnectorrulecreaterequestSignature) {
	o.Signature = &v
}

// GetSourceCode returns the SourceCode field value
func (o *Connectorruleresponse) GetSourceCode() Sourcecode {
	if o == nil {
		var ret Sourcecode
		return ret
	}

	return o.SourceCode
}

// GetSourceCodeOk returns a tuple with the SourceCode field value
// and a boolean to check if the value has been set.
func (o *Connectorruleresponse) GetSourceCodeOk() (*Sourcecode, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SourceCode, true
}

// SetSourceCode sets field value
func (o *Connectorruleresponse) SetSourceCode(v Sourcecode) {
	o.SourceCode = v
}

// GetAttributes returns the Attributes field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Connectorruleresponse) GetAttributes() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Connectorruleresponse) GetAttributesOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Attributes) {
		return map[string]interface{}{}, false
	}
	return o.Attributes, true
}

// HasAttributes returns a boolean if a field has been set.
func (o *Connectorruleresponse) HasAttributes() bool {
	if o != nil && !IsNil(o.Attributes) {
		return true
	}

	return false
}

// SetAttributes gets a reference to the given map[string]interface{} and assigns it to the Attributes field.
func (o *Connectorruleresponse) SetAttributes(v map[string]interface{}) {
	o.Attributes = v
}

// GetId returns the Id field value
func (o *Connectorruleresponse) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *Connectorruleresponse) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *Connectorruleresponse) SetId(v string) {
	o.Id = v
}

// GetCreated returns the Created field value
func (o *Connectorruleresponse) GetCreated() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Created
}

// GetCreatedOk returns a tuple with the Created field value
// and a boolean to check if the value has been set.
func (o *Connectorruleresponse) GetCreatedOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Created, true
}

// SetCreated sets field value
func (o *Connectorruleresponse) SetCreated(v string) {
	o.Created = v
}

// GetModified returns the Modified field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Connectorruleresponse) GetModified() string {
	if o == nil || IsNil(o.Modified.Get()) {
		var ret string
		return ret
	}
	return *o.Modified.Get()
}

// GetModifiedOk returns a tuple with the Modified field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Connectorruleresponse) GetModifiedOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Modified.Get(), o.Modified.IsSet()
}

// HasModified returns a boolean if a field has been set.
func (o *Connectorruleresponse) HasModified() bool {
	if o != nil && o.Modified.IsSet() {
		return true
	}

	return false
}

// SetModified gets a reference to the given NullableString and assigns it to the Modified field.
func (o *Connectorruleresponse) SetModified(v string) {
	o.Modified.Set(&v)
}
// SetModifiedNil sets the value for Modified to be an explicit nil
func (o *Connectorruleresponse) SetModifiedNil() {
	o.Modified.Set(nil)
}

// UnsetModified ensures that no value is present for Modified, not even an explicit nil
func (o *Connectorruleresponse) UnsetModified() {
	o.Modified.Unset()
}

func (o Connectorruleresponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Connectorruleresponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	if o.Description.IsSet() {
		toSerialize["description"] = o.Description.Get()
	}
	toSerialize["type"] = o.Type
	if !IsNil(o.Signature) {
		toSerialize["signature"] = o.Signature
	}
	toSerialize["sourceCode"] = o.SourceCode
	if o.Attributes != nil {
		toSerialize["attributes"] = o.Attributes
	}
	toSerialize["id"] = o.Id
	toSerialize["created"] = o.Created
	if o.Modified.IsSet() {
		toSerialize["modified"] = o.Modified.Get()
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *Connectorruleresponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"type",
		"sourceCode",
		"id",
		"created",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varConnectorruleresponse := _Connectorruleresponse{}

	err = json.Unmarshal(data, &varConnectorruleresponse)

	if err != nil {
		return err
	}

	*o = Connectorruleresponse(varConnectorruleresponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "name")
		delete(additionalProperties, "description")
		delete(additionalProperties, "type")
		delete(additionalProperties, "signature")
		delete(additionalProperties, "sourceCode")
		delete(additionalProperties, "attributes")
		delete(additionalProperties, "id")
		delete(additionalProperties, "created")
		delete(additionalProperties, "modified")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableConnectorruleresponse struct {
	value *Connectorruleresponse
	isSet bool
}

func (v NullableConnectorruleresponse) Get() *Connectorruleresponse {
	return v.value
}

func (v *NullableConnectorruleresponse) Set(val *Connectorruleresponse) {
	v.value = val
	v.isSet = true
}

func (v NullableConnectorruleresponse) IsSet() bool {
	return v.isSet
}

func (v *NullableConnectorruleresponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConnectorruleresponse(val *Connectorruleresponse) *NullableConnectorruleresponse {
	return &NullableConnectorruleresponse{value: val, isSet: true}
}

func (v NullableConnectorruleresponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConnectorruleresponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


