/*
Identity Security Cloud API - Sources

Use these APIs to interact with the Identity Security Cloud platform to achieve repeatable, automated processes with greater scalability. We encourage you to join the SailPoint Developer Community forum at https://developer.sailpoint.com/discuss to connect with other developers using our APIs.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api_sources_v1

import (
	"encoding/json"
)

// checks if the DependantappconnectionsAccountSource type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DependantappconnectionsAccountSource{}

// DependantappconnectionsAccountSource The Account Source of the connected Application
type DependantappconnectionsAccountSource struct {
	// Use this Account Source for password management
	UseForPasswordManagement *bool `json:"useForPasswordManagement,omitempty"`
	// A list of Password Policies for this Account Source
	PasswordPolicies []DependantappconnectionsAccountSourcePasswordPoliciesInner `json:"passwordPolicies,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _DependantappconnectionsAccountSource DependantappconnectionsAccountSource

// NewDependantappconnectionsAccountSource instantiates a new DependantappconnectionsAccountSource object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDependantappconnectionsAccountSource() *DependantappconnectionsAccountSource {
	this := DependantappconnectionsAccountSource{}
	var useForPasswordManagement bool = false
	this.UseForPasswordManagement = &useForPasswordManagement
	return &this
}

// NewDependantappconnectionsAccountSourceWithDefaults instantiates a new DependantappconnectionsAccountSource object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDependantappconnectionsAccountSourceWithDefaults() *DependantappconnectionsAccountSource {
	this := DependantappconnectionsAccountSource{}
	var useForPasswordManagement bool = false
	this.UseForPasswordManagement = &useForPasswordManagement
	return &this
}

// GetUseForPasswordManagement returns the UseForPasswordManagement field value if set, zero value otherwise.
func (o *DependantappconnectionsAccountSource) GetUseForPasswordManagement() bool {
	if o == nil || IsNil(o.UseForPasswordManagement) {
		var ret bool
		return ret
	}
	return *o.UseForPasswordManagement
}

// GetUseForPasswordManagementOk returns a tuple with the UseForPasswordManagement field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DependantappconnectionsAccountSource) GetUseForPasswordManagementOk() (*bool, bool) {
	if o == nil || IsNil(o.UseForPasswordManagement) {
		return nil, false
	}
	return o.UseForPasswordManagement, true
}

// HasUseForPasswordManagement returns a boolean if a field has been set.
func (o *DependantappconnectionsAccountSource) HasUseForPasswordManagement() bool {
	if o != nil && !IsNil(o.UseForPasswordManagement) {
		return true
	}

	return false
}

// SetUseForPasswordManagement gets a reference to the given bool and assigns it to the UseForPasswordManagement field.
func (o *DependantappconnectionsAccountSource) SetUseForPasswordManagement(v bool) {
	o.UseForPasswordManagement = &v
}

// GetPasswordPolicies returns the PasswordPolicies field value if set, zero value otherwise.
func (o *DependantappconnectionsAccountSource) GetPasswordPolicies() []DependantappconnectionsAccountSourcePasswordPoliciesInner {
	if o == nil || IsNil(o.PasswordPolicies) {
		var ret []DependantappconnectionsAccountSourcePasswordPoliciesInner
		return ret
	}
	return o.PasswordPolicies
}

// GetPasswordPoliciesOk returns a tuple with the PasswordPolicies field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DependantappconnectionsAccountSource) GetPasswordPoliciesOk() ([]DependantappconnectionsAccountSourcePasswordPoliciesInner, bool) {
	if o == nil || IsNil(o.PasswordPolicies) {
		return nil, false
	}
	return o.PasswordPolicies, true
}

// HasPasswordPolicies returns a boolean if a field has been set.
func (o *DependantappconnectionsAccountSource) HasPasswordPolicies() bool {
	if o != nil && !IsNil(o.PasswordPolicies) {
		return true
	}

	return false
}

// SetPasswordPolicies gets a reference to the given []DependantappconnectionsAccountSourcePasswordPoliciesInner and assigns it to the PasswordPolicies field.
func (o *DependantappconnectionsAccountSource) SetPasswordPolicies(v []DependantappconnectionsAccountSourcePasswordPoliciesInner) {
	o.PasswordPolicies = v
}

func (o DependantappconnectionsAccountSource) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DependantappconnectionsAccountSource) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.UseForPasswordManagement) {
		toSerialize["useForPasswordManagement"] = o.UseForPasswordManagement
	}
	if !IsNil(o.PasswordPolicies) {
		toSerialize["passwordPolicies"] = o.PasswordPolicies
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *DependantappconnectionsAccountSource) UnmarshalJSON(data []byte) (err error) {
	varDependantappconnectionsAccountSource := _DependantappconnectionsAccountSource{}

	err = json.Unmarshal(data, &varDependantappconnectionsAccountSource)

	if err != nil {
		return err
	}

	*o = DependantappconnectionsAccountSource(varDependantappconnectionsAccountSource)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "useForPasswordManagement")
		delete(additionalProperties, "passwordPolicies")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableDependantappconnectionsAccountSource struct {
	value *DependantappconnectionsAccountSource
	isSet bool
}

func (v NullableDependantappconnectionsAccountSource) Get() *DependantappconnectionsAccountSource {
	return v.value
}

func (v *NullableDependantappconnectionsAccountSource) Set(val *DependantappconnectionsAccountSource) {
	v.value = val
	v.isSet = true
}

func (v NullableDependantappconnectionsAccountSource) IsSet() bool {
	return v.isSet
}

func (v *NullableDependantappconnectionsAccountSource) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDependantappconnectionsAccountSource(val *DependantappconnectionsAccountSource) *NullableDependantappconnectionsAccountSource {
	return &NullableDependantappconnectionsAccountSource{value: val, isSet: true}
}

func (v NullableDependantappconnectionsAccountSource) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDependantappconnectionsAccountSource) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


