/*
Identity Security Cloud v2026 API

Testing HumanAccountDeletionApprovalConfigAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package api_v2026

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/sailpoint-oss/golang-sdk/v2"
)

func Test_api_v2026_HumanAccountDeletionApprovalConfigAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test HumanAccountDeletionApprovalConfigAPIService GetAccountDeleteApprovalConfig", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var sourceId string

		resp, httpRes, err := apiClient.HumanAccountDeletionApprovalConfigAPI.GetAccountDeleteApprovalConfig(context.Background(), sourceId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test HumanAccountDeletionApprovalConfigAPIService UpdateAccountDeletionApprovalConfig", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var sourceId string

		resp, httpRes, err := apiClient.HumanAccountDeletionApprovalConfigAPI.UpdateAccountDeletionApprovalConfig(context.Background(), sourceId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
