/*
Identity Security Cloud API - Intelligence

Use these APIs to interact with the Identity Security Cloud platform to achieve repeatable, automated processes with greater scalability. We encourage you to join the SailPoint Developer Community forum at https://developer.sailpoint.com/discuss to connect with other developers using our APIs.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package intelligence

import (
	"encoding/json"
	"fmt"
)

// checks if the IntelPrivilegedAccessSlice type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IntelPrivilegedAccessSlice{}

// IntelPrivilegedAccessSlice Full privileged access result embedded in the aggregate identity response.
type IntelPrivilegedAccessSlice struct {
	// Privileged access items for the identity.
	Items []IntelPrivilegedAccessItemWire `json:"items"`
	AdditionalProperties map[string]interface{}
}

type _IntelPrivilegedAccessSlice IntelPrivilegedAccessSlice

// NewIntelPrivilegedAccessSlice instantiates a new IntelPrivilegedAccessSlice object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIntelPrivilegedAccessSlice(items []IntelPrivilegedAccessItemWire) *IntelPrivilegedAccessSlice {
	this := IntelPrivilegedAccessSlice{}
	this.Items = items
	return &this
}

// NewIntelPrivilegedAccessSliceWithDefaults instantiates a new IntelPrivilegedAccessSlice object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIntelPrivilegedAccessSliceWithDefaults() *IntelPrivilegedAccessSlice {
	this := IntelPrivilegedAccessSlice{}
	return &this
}

// GetItems returns the Items field value
func (o *IntelPrivilegedAccessSlice) GetItems() []IntelPrivilegedAccessItemWire {
	if o == nil {
		var ret []IntelPrivilegedAccessItemWire
		return ret
	}

	return o.Items
}

// GetItemsOk returns a tuple with the Items field value
// and a boolean to check if the value has been set.
func (o *IntelPrivilegedAccessSlice) GetItemsOk() ([]IntelPrivilegedAccessItemWire, bool) {
	if o == nil {
		return nil, false
	}
	return o.Items, true
}

// SetItems sets field value
func (o *IntelPrivilegedAccessSlice) SetItems(v []IntelPrivilegedAccessItemWire) {
	o.Items = v
}

func (o IntelPrivilegedAccessSlice) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IntelPrivilegedAccessSlice) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["items"] = o.Items

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *IntelPrivilegedAccessSlice) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"items",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varIntelPrivilegedAccessSlice := _IntelPrivilegedAccessSlice{}

	err = json.Unmarshal(data, &varIntelPrivilegedAccessSlice)

	if err != nil {
		return err
	}

	*o = IntelPrivilegedAccessSlice(varIntelPrivilegedAccessSlice)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "items")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableIntelPrivilegedAccessSlice struct {
	value *IntelPrivilegedAccessSlice
	isSet bool
}

func (v NullableIntelPrivilegedAccessSlice) Get() *IntelPrivilegedAccessSlice {
	return v.value
}

func (v *NullableIntelPrivilegedAccessSlice) Set(val *IntelPrivilegedAccessSlice) {
	v.value = val
	v.isSet = true
}

func (v NullableIntelPrivilegedAccessSlice) IsSet() bool {
	return v.isSet
}

func (v *NullableIntelPrivilegedAccessSlice) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIntelPrivilegedAccessSlice(val *IntelPrivilegedAccessSlice) *NullableIntelPrivilegedAccessSlice {
	return &NullableIntelPrivilegedAccessSlice{value: val, isSet: true}
}

func (v NullableIntelPrivilegedAccessSlice) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIntelPrivilegedAccessSlice) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


