/*
IdentityNow Beta API

Use these APIs to interact with the IdentityNow platform to achieve repeatable, automated processes with greater scalability. These APIs are in beta and are subject to change. We encourage you to join the SailPoint Developer Community forum at https://developer.sailpoint.com/discuss to connect with other developers using our APIs.

API version: 3.1.0-beta
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package beta

import (
	"encoding/json"
)

// checks if the LeftPad type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LeftPad{}

// LeftPad struct for LeftPad
type LeftPad struct {
	// An integer value for the desired length of the final output string
	Length string `json:"length"`
	// A string value representing the character that the incoming data should be padded with to get to the desired length   If not provided, the transform will default to a single space (\" \") character for padding 
	Padding *string `json:"padding,omitempty"`
	// A value that indicates whether the transform logic should be re-evaluated every evening as part of the identity refresh process
	RequiresPeriodicRefresh *bool `json:"requiresPeriodicRefresh,omitempty"`
	// This is an optional attribute that can explicitly define the input data which will be fed into the transform logic. If input is not provided, the transform will take its input from the source and attribute combination configured via the UI.
	Input map[string]interface{} `json:"input,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _LeftPad LeftPad

// NewLeftPad instantiates a new LeftPad object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLeftPad(length string) *LeftPad {
	this := LeftPad{}
	this.Length = length
	var requiresPeriodicRefresh bool = false
	this.RequiresPeriodicRefresh = &requiresPeriodicRefresh
	return &this
}

// NewLeftPadWithDefaults instantiates a new LeftPad object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLeftPadWithDefaults() *LeftPad {
	this := LeftPad{}
	var requiresPeriodicRefresh bool = false
	this.RequiresPeriodicRefresh = &requiresPeriodicRefresh
	return &this
}

// GetLength returns the Length field value
func (o *LeftPad) GetLength() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Length
}

// GetLengthOk returns a tuple with the Length field value
// and a boolean to check if the value has been set.
func (o *LeftPad) GetLengthOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Length, true
}

// SetLength sets field value
func (o *LeftPad) SetLength(v string) {
	o.Length = v
}

// GetPadding returns the Padding field value if set, zero value otherwise.
func (o *LeftPad) GetPadding() string {
	if o == nil || isNil(o.Padding) {
		var ret string
		return ret
	}
	return *o.Padding
}

// GetPaddingOk returns a tuple with the Padding field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LeftPad) GetPaddingOk() (*string, bool) {
	if o == nil || isNil(o.Padding) {
		return nil, false
	}
	return o.Padding, true
}

// HasPadding returns a boolean if a field has been set.
func (o *LeftPad) HasPadding() bool {
	if o != nil && !isNil(o.Padding) {
		return true
	}

	return false
}

// SetPadding gets a reference to the given string and assigns it to the Padding field.
func (o *LeftPad) SetPadding(v string) {
	o.Padding = &v
}

// GetRequiresPeriodicRefresh returns the RequiresPeriodicRefresh field value if set, zero value otherwise.
func (o *LeftPad) GetRequiresPeriodicRefresh() bool {
	if o == nil || isNil(o.RequiresPeriodicRefresh) {
		var ret bool
		return ret
	}
	return *o.RequiresPeriodicRefresh
}

// GetRequiresPeriodicRefreshOk returns a tuple with the RequiresPeriodicRefresh field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LeftPad) GetRequiresPeriodicRefreshOk() (*bool, bool) {
	if o == nil || isNil(o.RequiresPeriodicRefresh) {
		return nil, false
	}
	return o.RequiresPeriodicRefresh, true
}

// HasRequiresPeriodicRefresh returns a boolean if a field has been set.
func (o *LeftPad) HasRequiresPeriodicRefresh() bool {
	if o != nil && !isNil(o.RequiresPeriodicRefresh) {
		return true
	}

	return false
}

// SetRequiresPeriodicRefresh gets a reference to the given bool and assigns it to the RequiresPeriodicRefresh field.
func (o *LeftPad) SetRequiresPeriodicRefresh(v bool) {
	o.RequiresPeriodicRefresh = &v
}

// GetInput returns the Input field value if set, zero value otherwise.
func (o *LeftPad) GetInput() map[string]interface{} {
	if o == nil || isNil(o.Input) {
		var ret map[string]interface{}
		return ret
	}
	return o.Input
}

// GetInputOk returns a tuple with the Input field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LeftPad) GetInputOk() (map[string]interface{}, bool) {
	if o == nil || isNil(o.Input) {
		return map[string]interface{}{}, false
	}
	return o.Input, true
}

// HasInput returns a boolean if a field has been set.
func (o *LeftPad) HasInput() bool {
	if o != nil && !isNil(o.Input) {
		return true
	}

	return false
}

// SetInput gets a reference to the given map[string]interface{} and assigns it to the Input field.
func (o *LeftPad) SetInput(v map[string]interface{}) {
	o.Input = v
}

func (o LeftPad) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LeftPad) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["length"] = o.Length
	if !isNil(o.Padding) {
		toSerialize["padding"] = o.Padding
	}
	if !isNil(o.RequiresPeriodicRefresh) {
		toSerialize["requiresPeriodicRefresh"] = o.RequiresPeriodicRefresh
	}
	if !isNil(o.Input) {
		toSerialize["input"] = o.Input
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *LeftPad) UnmarshalJSON(bytes []byte) (err error) {
	varLeftPad := _LeftPad{}

	if err = json.Unmarshal(bytes, &varLeftPad); err == nil {
		*o = LeftPad(varLeftPad)
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {
		delete(additionalProperties, "length")
		delete(additionalProperties, "padding")
		delete(additionalProperties, "requiresPeriodicRefresh")
		delete(additionalProperties, "input")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableLeftPad struct {
	value *LeftPad
	isSet bool
}

func (v NullableLeftPad) Get() *LeftPad {
	return v.value
}

func (v *NullableLeftPad) Set(val *LeftPad) {
	v.value = val
	v.isSet = true
}

func (v NullableLeftPad) IsSet() bool {
	return v.isSet
}

func (v *NullableLeftPad) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLeftPad(val *LeftPad) *NullableLeftPad {
	return &NullableLeftPad{value: val, isSet: true}
}

func (v NullableLeftPad) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLeftPad) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


