/*
Identity Security Cloud API - Declassify Source

Use these APIs to interact with the Identity Security Cloud platform to achieve repeatable, automated processes with greater scalability. We encourage you to join the SailPoint Developer Community forum at https://developer.sailpoint.com/discuss to connect with other developers using our APIs.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api_declassify_source

import (
	"encoding/json"
)

// checks if the SendDeclassifyMachineAccountFromSourceV1429Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SendDeclassifyMachineAccountFromSourceV1429Response{}

// SendDeclassifyMachineAccountFromSourceV1429Response struct for SendDeclassifyMachineAccountFromSourceV1429Response
type SendDeclassifyMachineAccountFromSourceV1429Response struct {
	// A message describing the error
	Message interface{} `json:"message,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _SendDeclassifyMachineAccountFromSourceV1429Response SendDeclassifyMachineAccountFromSourceV1429Response

// NewSendDeclassifyMachineAccountFromSourceV1429Response instantiates a new SendDeclassifyMachineAccountFromSourceV1429Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSendDeclassifyMachineAccountFromSourceV1429Response() *SendDeclassifyMachineAccountFromSourceV1429Response {
	this := SendDeclassifyMachineAccountFromSourceV1429Response{}
	return &this
}

// NewSendDeclassifyMachineAccountFromSourceV1429ResponseWithDefaults instantiates a new SendDeclassifyMachineAccountFromSourceV1429Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSendDeclassifyMachineAccountFromSourceV1429ResponseWithDefaults() *SendDeclassifyMachineAccountFromSourceV1429Response {
	this := SendDeclassifyMachineAccountFromSourceV1429Response{}
	return &this
}

// GetMessage returns the Message field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SendDeclassifyMachineAccountFromSourceV1429Response) GetMessage() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SendDeclassifyMachineAccountFromSourceV1429Response) GetMessageOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return &o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *SendDeclassifyMachineAccountFromSourceV1429Response) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given interface{} and assigns it to the Message field.
func (o *SendDeclassifyMachineAccountFromSourceV1429Response) SetMessage(v interface{}) {
	o.Message = v
}

func (o SendDeclassifyMachineAccountFromSourceV1429Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SendDeclassifyMachineAccountFromSourceV1429Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Message != nil {
		toSerialize["message"] = o.Message
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *SendDeclassifyMachineAccountFromSourceV1429Response) UnmarshalJSON(data []byte) (err error) {
	varSendDeclassifyMachineAccountFromSourceV1429Response := _SendDeclassifyMachineAccountFromSourceV1429Response{}

	err = json.Unmarshal(data, &varSendDeclassifyMachineAccountFromSourceV1429Response)

	if err != nil {
		return err
	}

	*o = SendDeclassifyMachineAccountFromSourceV1429Response(varSendDeclassifyMachineAccountFromSourceV1429Response)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "message")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableSendDeclassifyMachineAccountFromSourceV1429Response struct {
	value *SendDeclassifyMachineAccountFromSourceV1429Response
	isSet bool
}

func (v NullableSendDeclassifyMachineAccountFromSourceV1429Response) Get() *SendDeclassifyMachineAccountFromSourceV1429Response {
	return v.value
}

func (v *NullableSendDeclassifyMachineAccountFromSourceV1429Response) Set(val *SendDeclassifyMachineAccountFromSourceV1429Response) {
	v.value = val
	v.isSet = true
}

func (v NullableSendDeclassifyMachineAccountFromSourceV1429Response) IsSet() bool {
	return v.isSet
}

func (v *NullableSendDeclassifyMachineAccountFromSourceV1429Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSendDeclassifyMachineAccountFromSourceV1429Response(val *SendDeclassifyMachineAccountFromSourceV1429Response) *NullableSendDeclassifyMachineAccountFromSourceV1429Response {
	return &NullableSendDeclassifyMachineAccountFromSourceV1429Response{value: val, isSet: true}
}

func (v NullableSendDeclassifyMachineAccountFromSourceV1429Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSendDeclassifyMachineAccountFromSourceV1429Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


