/*
Identity Security Cloud V2025 API

Use these APIs to interact with the Identity Security Cloud platform to achieve repeatable, automated processes with greater scalability. We encourage you to join the SailPoint Developer Community forum at https://developer.sailpoint.com/discuss to connect with other developers using our APIs.

API version: v2025
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api_v2025

import (
	"encoding/json"
)

// checks if the AccountAllOfIdentity type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AccountAllOfIdentity{}

// AccountAllOfIdentity The identity this account is correlated to
type AccountAllOfIdentity struct {
	// The ID of the identity
	Id *string `json:"id,omitempty"`
	// The type of object being referenced
	Type *string `json:"type,omitempty"`
	// display name of identity
	Name *string `json:"name,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _AccountAllOfIdentity AccountAllOfIdentity

// NewAccountAllOfIdentity instantiates a new AccountAllOfIdentity object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAccountAllOfIdentity() *AccountAllOfIdentity {
	this := AccountAllOfIdentity{}
	return &this
}

// NewAccountAllOfIdentityWithDefaults instantiates a new AccountAllOfIdentity object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAccountAllOfIdentityWithDefaults() *AccountAllOfIdentity {
	this := AccountAllOfIdentity{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *AccountAllOfIdentity) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountAllOfIdentity) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *AccountAllOfIdentity) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *AccountAllOfIdentity) SetId(v string) {
	o.Id = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *AccountAllOfIdentity) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountAllOfIdentity) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *AccountAllOfIdentity) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *AccountAllOfIdentity) SetType(v string) {
	o.Type = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *AccountAllOfIdentity) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountAllOfIdentity) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *AccountAllOfIdentity) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *AccountAllOfIdentity) SetName(v string) {
	o.Name = &v
}

func (o AccountAllOfIdentity) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AccountAllOfIdentity) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *AccountAllOfIdentity) UnmarshalJSON(data []byte) (err error) {
	varAccountAllOfIdentity := _AccountAllOfIdentity{}

	err = json.Unmarshal(data, &varAccountAllOfIdentity)

	if err != nil {
		return err
	}

	*o = AccountAllOfIdentity(varAccountAllOfIdentity)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "type")
		delete(additionalProperties, "name")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableAccountAllOfIdentity struct {
	value *AccountAllOfIdentity
	isSet bool
}

func (v NullableAccountAllOfIdentity) Get() *AccountAllOfIdentity {
	return v.value
}

func (v *NullableAccountAllOfIdentity) Set(val *AccountAllOfIdentity) {
	v.value = val
	v.isSet = true
}

func (v NullableAccountAllOfIdentity) IsSet() bool {
	return v.isSet
}

func (v *NullableAccountAllOfIdentity) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAccountAllOfIdentity(val *AccountAllOfIdentity) *NullableAccountAllOfIdentity {
	return &NullableAccountAllOfIdentity{value: val, isSet: true}
}

func (v NullableAccountAllOfIdentity) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAccountAllOfIdentity) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


