/*
Identity Security Cloud API - Connector Customizers

Use these APIs to interact with the Identity Security Cloud platform to achieve repeatable, automated processes with greater scalability. We encourage you to join the SailPoint Developer Community forum at https://developer.sailpoint.com/discuss to connect with other developers using our APIs.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api_connector_customizers_v1

import (
	"encoding/json"
	"time"
)

// checks if the Connectorcustomizercreateresponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Connectorcustomizercreateresponse{}

// Connectorcustomizercreateresponse ConnectorCustomizerResponse
type Connectorcustomizercreateresponse struct {
	// the ID of connector customizer.
	Id *string `json:"id,omitempty"`
	// name of the connector customizer.
	Name *string `json:"name,omitempty"`
	// Connector customizer tenant id.
	TenantID *string `json:"tenantID,omitempty"`
	// Date-time when the connector customizer was created.
	Created *time.Time `json:"created,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _Connectorcustomizercreateresponse Connectorcustomizercreateresponse

// NewConnectorcustomizercreateresponse instantiates a new Connectorcustomizercreateresponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConnectorcustomizercreateresponse() *Connectorcustomizercreateresponse {
	this := Connectorcustomizercreateresponse{}
	return &this
}

// NewConnectorcustomizercreateresponseWithDefaults instantiates a new Connectorcustomizercreateresponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConnectorcustomizercreateresponseWithDefaults() *Connectorcustomizercreateresponse {
	this := Connectorcustomizercreateresponse{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *Connectorcustomizercreateresponse) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Connectorcustomizercreateresponse) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *Connectorcustomizercreateresponse) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *Connectorcustomizercreateresponse) SetId(v string) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *Connectorcustomizercreateresponse) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Connectorcustomizercreateresponse) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *Connectorcustomizercreateresponse) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *Connectorcustomizercreateresponse) SetName(v string) {
	o.Name = &v
}

// GetTenantID returns the TenantID field value if set, zero value otherwise.
func (o *Connectorcustomizercreateresponse) GetTenantID() string {
	if o == nil || IsNil(o.TenantID) {
		var ret string
		return ret
	}
	return *o.TenantID
}

// GetTenantIDOk returns a tuple with the TenantID field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Connectorcustomizercreateresponse) GetTenantIDOk() (*string, bool) {
	if o == nil || IsNil(o.TenantID) {
		return nil, false
	}
	return o.TenantID, true
}

// HasTenantID returns a boolean if a field has been set.
func (o *Connectorcustomizercreateresponse) HasTenantID() bool {
	if o != nil && !IsNil(o.TenantID) {
		return true
	}

	return false
}

// SetTenantID gets a reference to the given string and assigns it to the TenantID field.
func (o *Connectorcustomizercreateresponse) SetTenantID(v string) {
	o.TenantID = &v
}

// GetCreated returns the Created field value if set, zero value otherwise.
func (o *Connectorcustomizercreateresponse) GetCreated() time.Time {
	if o == nil || IsNil(o.Created) {
		var ret time.Time
		return ret
	}
	return *o.Created
}

// GetCreatedOk returns a tuple with the Created field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Connectorcustomizercreateresponse) GetCreatedOk() (*time.Time, bool) {
	if o == nil || IsNil(o.Created) {
		return nil, false
	}
	return o.Created, true
}

// HasCreated returns a boolean if a field has been set.
func (o *Connectorcustomizercreateresponse) HasCreated() bool {
	if o != nil && !IsNil(o.Created) {
		return true
	}

	return false
}

// SetCreated gets a reference to the given time.Time and assigns it to the Created field.
func (o *Connectorcustomizercreateresponse) SetCreated(v time.Time) {
	o.Created = &v
}

func (o Connectorcustomizercreateresponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Connectorcustomizercreateresponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.TenantID) {
		toSerialize["tenantID"] = o.TenantID
	}
	if !IsNil(o.Created) {
		toSerialize["created"] = o.Created
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *Connectorcustomizercreateresponse) UnmarshalJSON(data []byte) (err error) {
	varConnectorcustomizercreateresponse := _Connectorcustomizercreateresponse{}

	err = json.Unmarshal(data, &varConnectorcustomizercreateresponse)

	if err != nil {
		return err
	}

	*o = Connectorcustomizercreateresponse(varConnectorcustomizercreateresponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "name")
		delete(additionalProperties, "tenantID")
		delete(additionalProperties, "created")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableConnectorcustomizercreateresponse struct {
	value *Connectorcustomizercreateresponse
	isSet bool
}

func (v NullableConnectorcustomizercreateresponse) Get() *Connectorcustomizercreateresponse {
	return v.value
}

func (v *NullableConnectorcustomizercreateresponse) Set(val *Connectorcustomizercreateresponse) {
	v.value = val
	v.isSet = true
}

func (v NullableConnectorcustomizercreateresponse) IsSet() bool {
	return v.isSet
}

func (v *NullableConnectorcustomizercreateresponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConnectorcustomizercreateresponse(val *Connectorcustomizercreateresponse) *NullableConnectorcustomizercreateresponse {
	return &NullableConnectorcustomizercreateresponse{value: val, isSet: true}
}

func (v NullableConnectorcustomizercreateresponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConnectorcustomizercreateresponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


