/*
Identity Security Cloud API - JIT Access

Use these APIs to interact with the Identity Security Cloud platform to achieve repeatable, automated processes with greater scalability. We encourage you to join the SailPoint Developer Community forum at https://developer.sailpoint.com/discuss to connect with other developers using our APIs.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package jit_access

import (
	"encoding/json"
)

// checks if the GetJitActivationConfigV1429Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetJitActivationConfigV1429Response{}

// GetJitActivationConfigV1429Response struct for GetJitActivationConfigV1429Response
type GetJitActivationConfigV1429Response struct {
	// A message describing the error
	Message interface{} `json:"message,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _GetJitActivationConfigV1429Response GetJitActivationConfigV1429Response

// NewGetJitActivationConfigV1429Response instantiates a new GetJitActivationConfigV1429Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetJitActivationConfigV1429Response() *GetJitActivationConfigV1429Response {
	this := GetJitActivationConfigV1429Response{}
	return &this
}

// NewGetJitActivationConfigV1429ResponseWithDefaults instantiates a new GetJitActivationConfigV1429Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetJitActivationConfigV1429ResponseWithDefaults() *GetJitActivationConfigV1429Response {
	this := GetJitActivationConfigV1429Response{}
	return &this
}

// GetMessage returns the Message field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetJitActivationConfigV1429Response) GetMessage() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetJitActivationConfigV1429Response) GetMessageOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return &o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *GetJitActivationConfigV1429Response) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given interface{} and assigns it to the Message field.
func (o *GetJitActivationConfigV1429Response) SetMessage(v interface{}) {
	o.Message = v
}

func (o GetJitActivationConfigV1429Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetJitActivationConfigV1429Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Message != nil {
		toSerialize["message"] = o.Message
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GetJitActivationConfigV1429Response) UnmarshalJSON(data []byte) (err error) {
	varGetJitActivationConfigV1429Response := _GetJitActivationConfigV1429Response{}

	err = json.Unmarshal(data, &varGetJitActivationConfigV1429Response)

	if err != nil {
		return err
	}

	*o = GetJitActivationConfigV1429Response(varGetJitActivationConfigV1429Response)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "message")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGetJitActivationConfigV1429Response struct {
	value *GetJitActivationConfigV1429Response
	isSet bool
}

func (v NullableGetJitActivationConfigV1429Response) Get() *GetJitActivationConfigV1429Response {
	return v.value
}

func (v *NullableGetJitActivationConfigV1429Response) Set(val *GetJitActivationConfigV1429Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetJitActivationConfigV1429Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetJitActivationConfigV1429Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetJitActivationConfigV1429Response(val *GetJitActivationConfigV1429Response) *NullableGetJitActivationConfigV1429Response {
	return &NullableGetJitActivationConfigV1429Response{value: val, isSet: true}
}

func (v NullableGetJitActivationConfigV1429Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetJitActivationConfigV1429Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


