name: "Build Go SDK"
description: "Build all API versions of the Go SDK from OpenAPI specs"

inputs:
  api-specs-path:
    description: "Path to the checked-out api-specs repository"
    required: false
    default: "api-specs"
  skip-tests:
    description: "Skip running tests after building"
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - name: Set up Node
      uses: actions/setup-node@v6
      with:
        node-version: "24"

    - name: Download OpenAPI Generator
      shell: bash
      run: |
        wget -q https://repo1.maven.org/maven2/org/openapitools/openapi-generator-cli/7.12.0/openapi-generator-cli-7.12.0.jar -O openapi-generator-cli.jar

    - name: Run Prescript
      shell: bash
      run: node sdk-resources/prescript.js ${{ inputs.api-specs-path }}/idn

    - name: Build V3 SDK
      shell: bash
      run: |
        rm -rf ./api_v3
        java -jar openapi-generator-cli.jar generate \
          -i ${{ inputs.api-specs-path }}/idn/sailpoint-api.v3.yaml \
          -g go -o api_v3 \
          --global-property skipFormModel=false,apiDocs=true,modelDocs=true \
          --config sdk-resources/v3-config.yaml
        node sdk-resources/postscript.js ./api_v3

    - name: Build Beta SDK
      shell: bash
      run: |
        rm -rf ./api_beta
        java -jar openapi-generator-cli.jar generate \
          -i ${{ inputs.api-specs-path }}/idn/sailpoint-api.beta.yaml \
          -g go -o api_beta \
          --global-property skipFormModel=false,apiDocs=true,modelDocs=true \
          --config sdk-resources/beta-config.yaml
        node sdk-resources/postscript.js ./api_beta

    - name: Build V2024 SDK
      shell: bash
      run: |
        rm -rf ./api_v2024
        java -jar openapi-generator-cli.jar generate \
          -i ${{ inputs.api-specs-path }}/idn/sailpoint-api.v2024.yaml \
          -g go -o api_v2024 \
          --global-property skipFormModel=false,apiDocs=true,modelDocs=true \
          --config sdk-resources/v2024-config.yaml
        node sdk-resources/postscript.js ./api_v2024

    - name: Build V2025 SDK
      shell: bash
      run: |
        rm -rf ./api_v2025
        java -jar openapi-generator-cli.jar generate \
          -i ${{ inputs.api-specs-path }}/idn/sailpoint-api.v2025.yaml \
          -g go -o api_v2025 \
          --global-property skipFormModel=false,apiDocs=true,modelDocs=true \
          --config sdk-resources/v2025-config.yaml
        node sdk-resources/postscript.js ./api_v2025

    - name: Build Generic SDK
      shell: bash
      run: |
        rm -rf ./api_generic
        java -jar openapi-generator-cli.jar generate \
          -i sdk-resources/generic-api.yaml \
          -g go -o api_generic \
          --global-property skipFormModel=false,apiDocs=true,modelDocs=true \
          --config sdk-resources/generic-config.yaml
        node sdk-resources/postscript.js ./api_generic

    - name: Build V2026 SDK
      shell: bash
      run: |
        rm -rf ./api_v2026
        java -jar openapi-generator-cli.jar generate \
          -i ${{ inputs.api-specs-path }}/idn/sailpoint-api.v2026.yaml \
          -g go -o api_v2026 \
          --global-property skipFormModel=false,apiDocs=true,modelDocs=true \
          --config sdk-resources/v2026-config.yaml
        node sdk-resources/postscript.js ./api_v2026

    - name: Build and Test
      shell: bash
      run: |
        go get -d ./...
        go install
        if [ "${{ inputs.skip-tests }}" != "true" ]; then
          go test
        fi
