/*
Identity Security Cloud API - Triggers

Use these APIs to interact with the Identity Security Cloud platform to achieve repeatable, automated processes with greater scalability. We encourage you to join the SailPoint Developer Community forum at https://developer.sailpoint.com/discuss to connect with other developers using our APIs.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api_triggers_v1

import (
	"encoding/json"
	"time"
	"fmt"
)

// checks if the Sourcecreated type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Sourcecreated{}

// Sourcecreated struct for Sourcecreated
type Sourcecreated struct {
	// The unique ID of the source.
	Id string `json:"id"`
	// Human friendly name of the source.
	Name string `json:"name"`
	// The connection type.
	Type string `json:"type"`
	// The date and time the source was created.
	Created time.Time `json:"created"`
	// The connector type used to connect to the source.
	Connector string `json:"connector"`
	Actor SourcecreatedActor `json:"actor"`
	AdditionalProperties map[string]interface{}
}

type _Sourcecreated Sourcecreated

// NewSourcecreated instantiates a new Sourcecreated object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSourcecreated(id string, name string, type_ string, created time.Time, connector string, actor SourcecreatedActor) *Sourcecreated {
	this := Sourcecreated{}
	this.Id = id
	this.Name = name
	this.Type = type_
	this.Created = created
	this.Connector = connector
	this.Actor = actor
	return &this
}

// NewSourcecreatedWithDefaults instantiates a new Sourcecreated object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSourcecreatedWithDefaults() *Sourcecreated {
	this := Sourcecreated{}
	return &this
}

// GetId returns the Id field value
func (o *Sourcecreated) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *Sourcecreated) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *Sourcecreated) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *Sourcecreated) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *Sourcecreated) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *Sourcecreated) SetName(v string) {
	o.Name = v
}

// GetType returns the Type field value
func (o *Sourcecreated) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *Sourcecreated) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *Sourcecreated) SetType(v string) {
	o.Type = v
}

// GetCreated returns the Created field value
func (o *Sourcecreated) GetCreated() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.Created
}

// GetCreatedOk returns a tuple with the Created field value
// and a boolean to check if the value has been set.
func (o *Sourcecreated) GetCreatedOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Created, true
}

// SetCreated sets field value
func (o *Sourcecreated) SetCreated(v time.Time) {
	o.Created = v
}

// GetConnector returns the Connector field value
func (o *Sourcecreated) GetConnector() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Connector
}

// GetConnectorOk returns a tuple with the Connector field value
// and a boolean to check if the value has been set.
func (o *Sourcecreated) GetConnectorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Connector, true
}

// SetConnector sets field value
func (o *Sourcecreated) SetConnector(v string) {
	o.Connector = v
}

// GetActor returns the Actor field value
func (o *Sourcecreated) GetActor() SourcecreatedActor {
	if o == nil {
		var ret SourcecreatedActor
		return ret
	}

	return o.Actor
}

// GetActorOk returns a tuple with the Actor field value
// and a boolean to check if the value has been set.
func (o *Sourcecreated) GetActorOk() (*SourcecreatedActor, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Actor, true
}

// SetActor sets field value
func (o *Sourcecreated) SetActor(v SourcecreatedActor) {
	o.Actor = v
}

func (o Sourcecreated) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Sourcecreated) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	toSerialize["type"] = o.Type
	toSerialize["created"] = o.Created
	toSerialize["connector"] = o.Connector
	toSerialize["actor"] = o.Actor

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *Sourcecreated) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"name",
		"type",
		"created",
		"connector",
		"actor",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSourcecreated := _Sourcecreated{}

	err = json.Unmarshal(data, &varSourcecreated)

	if err != nil {
		return err
	}

	*o = Sourcecreated(varSourcecreated)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "name")
		delete(additionalProperties, "type")
		delete(additionalProperties, "created")
		delete(additionalProperties, "connector")
		delete(additionalProperties, "actor")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableSourcecreated struct {
	value *Sourcecreated
	isSet bool
}

func (v NullableSourcecreated) Get() *Sourcecreated {
	return v.value
}

func (v *NullableSourcecreated) Set(val *Sourcecreated) {
	v.value = val
	v.isSet = true
}

func (v NullableSourcecreated) IsSet() bool {
	return v.isSet
}

func (v *NullableSourcecreated) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSourcecreated(val *Sourcecreated) *NullableSourcecreated {
	return &NullableSourcecreated{value: val, isSet: true}
}

func (v NullableSourcecreated) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSourcecreated) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


