name: "Push Go SDK Docs to Developer Portal"

permissions:
  contents: write
  actions: read

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  push_spec_workflow:
    name: Push API spec changes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
          path: golang-sdk

      - name: Checkout API Specs Repo
        uses: actions/checkout@v2
        with:
          repository: sailpoint-oss/developer.sailpoint.com
          path: developer-community
          ref: main

      - name: Install rsync
        run: sudo apt update && sudo apt install -y rsync grsync

      - name: Sync files between folders
        run: |
          # V3
          rsync -cav --delete golang-sdk/api_v3/docs/Methods developer-community/docs/tools/sdk/go/Reference/V3
          rsync -cav --delete golang-sdk/api_v3/docs/Models  developer-community/docs/tools/sdk/go/Reference/V3
          rsync -av  golang-sdk/api_v3/docs/Examples/go_code_examples_overlay.yaml developer-community/static/code-examples/v3/

          # Beta
          rsync -cav --delete golang-sdk/api_beta/docs/Methods developer-community/docs/tools/sdk/go/Reference/Beta
          rsync -cav --delete golang-sdk/api_beta/docs/Models  developer-community/docs/tools/sdk/go/Reference/Beta
          rsync -av  golang-sdk/api_beta/docs/Examples/go_code_examples_overlay.yaml developer-community/static/code-examples/beta/

          # V2024
          rsync -cav --delete golang-sdk/api_v2024/docs/Methods developer-community/docs/tools/sdk/go/Reference/V2024
          rsync -cav --delete golang-sdk/api_v2024/docs/Models  developer-community/docs/tools/sdk/go/Reference/V2024
          rsync -av  golang-sdk/api_v2024/docs/Examples/go_code_examples_overlay.yaml developer-community/static/code-examples/v2024/

          # V2025
          rsync -cav --delete golang-sdk/api_v2025/docs/Methods developer-community/docs/tools/sdk/go/Reference/V2025
          rsync -cav --delete golang-sdk/api_v2025/docs/Models  developer-community/docs/tools/sdk/go/Reference/V2025
          rsync -av  golang-sdk/api_v2025/docs/Examples/go_code_examples_overlay.yaml developer-community/static/code-examples/v2025/

      - name: Check for changes and commit if any
        run: |
          cd developer-community
          if git diff --quiet; then
            echo "No changes to commit."
            exit 0
          fi
          git config --unset-all http.https://github.com/.extraheader
          git config --local user.email "devrel-service@sailpoint.com"
          git config --local user.name "developer-relations-sp"
          git add .
          git commit -m "Update Go SDK docs: ${{ github.run_id }}"
          git remote set-url origin https://${{ secrets.DEVREL_SERVICE_TOKEN }}@github.com/sailpoint-oss/developer.sailpoint.com.git
          git push

  publish-failure:
    name: Notify on failure
    runs-on: ubuntu-latest
    needs: push_spec_workflow
    if: ${{ always() && (needs.push_spec_workflow.result == 'failure' || needs.push_spec_workflow.result == 'timed_out') }}
    steps:
      - name: Invoke GithubNotificationsFunction Lambda
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            -d '{
              "workflowName": "${{ github.job }}",
              "repositoryName": "${{ github.event.repository.name }}",
              "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
            }' \
            "${{ secrets.NOTIFICATIONS_FUNCTION_URL }}"
